"""Import P2000 abbreviations from Bommel database."""

import logging

logger = logging.getLogger(__name__)

# P2000 abbreviations from https://p2000.bommel.net/afkortingen.php
ABBREVIATIONS = {
    # A
    "A&A": "Adviseur en Assistentie functionaris",
    "AB": "Adembescherming(svoertuig)",
    "ABVV": "Uitvoering onder de Algemene Berging en Vervoerscondities",
    "AC": "Alarmcentrale (BRW) / Actiecentrum",
    "ACDT": "Algemeen commandant",
    "ACP": "Algemeen Christelijke Politiebond",
    "AE": "Aanhoudingseenheid (politie)",
    "AG": "Adviseur Gevaarlijke Stoffen (BRW)",
    "AGS": "Adviseur Gevaarlijke Stoffen (BRW)",
    "AHV": "Ambulance Hulpverlening",
    "AID": "Algemene Inspectiedienst",
    "AIVD": "Algemene Inlichtingen- en Veiligheidsdienst",
    "AL": "Autoladder",
    "AMBU": "Ambulance",
    "ANPV": "Algemene Nederlandse Politievereniging",
    "APV": "Algemene Plaatselijke Verordening",
    "ARB": "Ambtenaar Rampenbestrijding",
    "AT": "Arrestatieteam",
    "AVLS": "Automatisch Voertuig Locatiesysteem",
    "AZ": "Ambulancezorg",
    "AZC": "Asielzoekerscentrum",
    # B
    "BBE-K": "Bijzondere Bijstandseenheid Krijgsmacht",
    "BBE-M": "Bijzondere Bijstandseenheid Korps Mariniers",
    "BBE-P": "Bijzondere Bijstandseenheid Politie",
    "BBE-SIE": "Bijzondere Bijstandseenheid Snelle Interventie Eenheid",
    "BBO": "Basis Beroeps Opleiding",
    "BC": "Bureauchef (van politie)",
    "BGM": "Burgemeester",
    "BHV": "Bedrijfshulpverlening",
    "BLS": "Basic Life Support",
    "BO": "Bijzondere opdracht",
    "BOA": "Buitengewone Opsporingsamtenaar",
    "BOD": "Bureau Operationele Dienst",
    "BOS": "Benzine, olie en smeermiddelen",
    "BOT": "Bedrijfs opvang team / Bijzonder Ondersteuningsteam",
    "BRV": "Brandweervaartuig",
    "BRW": "Brandweer",
    "BRZO": "Besluitrisico Zware Ongevallen",
    "BSB": "Brigade Speciale Beveiligingsopdrachten (KMAR)",
    "BTBE": "Bijzondere Technische Bijstandseenheid (Politie)",
    "BTGV": "Bijzondere Tactiek Gevaarlijke Verdachten (Politie)",
    "BUD": "Bureau Uitvoerende Dienst (politie)",
    "BVD": "Bevelvoerder Van Dienst (BRW)",
    "BWR": "Brandweer",
    "BZK": "Ministerie van Binnenlandse Zaken en Koninkrijksrelaties",
    # C
    "C2000": "Communicatiesysteem hulpverleningsinstanties",
    "CB": "Coördinerend burgemeester",
    "CBR": "Centraal Bureau Rijbewijzen",
    "CBRN": "Chemisch Biologisch Radiologisch Nucleair",
    "CCB": "Conflict- en Crisisbeheersing",
    "CC": "Compagnie-commandant",
    "CCK": "Calamiteiten Commando / Controle Kamer",
    "CDT": "Commandant (BRW)",
    "CE": "Combinatie Eenheid (TS en HV)",
    "CHvD": "Chef van Dienst",
    "CID": "Criminelen Informatiedienst",
    "CMI": "Centraal Meldpunt Incident Management",
    "CMK": "Centrale Meldkamer",
    "CMV": "Centraal Meldpunt Vrachtwagenberging",
    "COH": "Commando Haakarmbak",
    "COPI": "Coördinatie Plaats Incident",
    "CP": "Commando Post",
    "CPR": "Calamiteitenplan Rail",
    "CvD": "Commandant van Dienst",
    "CvDG": "Commandant van Dienst Geneeskundig",
    # D
    "DA": "Dienstauto",
    "DB": "Dienstbus",
    "DCMR": "Dienst Centraal Milieubeheer Rijnmond",
    "DECO": "Decontaminatie",
    "DGVP": "Dienst Geneeskundige Verzorging Politie",
    "DHV": "Directe Hulpverlening",
    "DIM": "Detectie Identificatie en Monitoring team",
    "DJI": "Dienst Justitie Inrichtingen",
    "DKDB": "Dienst Koninklijke en Diplomatieke Beveiliging",
    "DPA": "Dompelpomp Aanhanger",
    "DPU": "Dompelpomp Unit",
    "DTG": "Datum-tijdgroep",
    "DVI": "Disaster Victim Identification",
    # E
    "EBV": "Extra beveiligd vervoer",
    "ECD": "Economische Controledienst",
    "EHAD": "Eerste Hulp Aan Drenkelingen",
    "EHBI": "Eerste Hulp Bij (milieu) Incidenten",
    "EHBO": "Eerste Hulp Bij Ongevallen",
    "EHD": "Eerstehulpdienst",
    "EHV": "Eerstehulpverlening",
    "EOC": "Opruimingscommando (luchtmacht)",
    "EOD": "Explosieven Opruimingsdienst",
    # F
    "FDN": "Federatie Dierenambulances Nederland",
    "FIOD": "Fiscale Inlichtingen- en Opsporingsdienst",
    # G
    "GAC": "Gemeenschappelijk actiecentrum",
    "GAGS": "Gezondheidskundig Adviseur Gevaarlijke Stoffen",
    "GB": "Grote Brand",
    "GBO": "Groep Bijzondere Opdrachten (politie)",
    "GBT": "Gemeentelijk beleidsteam",
    "GCC": "Gemeentelijk Coördinatiecentrum",
    "GCS": "Gemeentelijke crisisstaf",
    "GCVD": "Geneeskundige commandant van dienst",
    "GGD": "Gemeentelijke Geneeskundige Gezondheidsdienst",
    "GGZ": "Geestelijke Gezondheidszorg",
    "GHOR": "Geneeskundige hulpverlening bij ongevallen en rampen",
    "GM": "Gereedschap / Materiaalwagen",
    "GMK": "Gemeenschappelijke Meldkamer",
    "GMS": "Geïntegreerd Meldkamersysteem",
    "GN": "Gewondennest",
    "GNK": "Geneeskundig",
    "GRIP": "Gecoördineerde Regionale Incidentenbestrijdingsprocedure",
    "GSD": "Gemeentelijke sociale dienst",
    "GSH": "Gevaarlijke Stoffen Haakarmbak",
    "GSO": "Grootschalig Optreden",
    # H
    "HA": "Haakarm chassis (voertuig)",
    "HALT": "Het Alternatief",
    "HAP": "Huisartsenpost",
    "HDL": "Handhavingsdienst Luchtvaart",
    "HGA": "Hoofd geneeskundige aangelegenheden",
    "HIvD": "Hoofdinspecteur van dienst",
    "HKS": "Herkenningssysteem",
    "HOD": "Hoofdofficier van Dienst",
    "HOVD": "Hoofdofficier van Dienst",
    "HRB": "Hoog Risico Beveiliging (KMAR)",
    "HTT": "Helikopter Traumateam",
    "HVH": "Hulpverleningshaakarmbak (BRW)",
    "HV": "Hulpverleningsvoertuig",
    "HW": "Hoogwerker",
    # I
    "IBT": "Intern Bijstandsteam (Justitie)",
    "ICMS": "Intensivering Civiel Militaire Samenwerking",
    "IM": "Incident Management",
    "IND": "Immigratie & Naturalisatiedienst",
    # K
    "KB": "Kleine brand",
    "KC": "Korpschef (van politie)",
    "KLPD": "Korps Landelijke Politiediensten",
    "KMAR": "Koninklijke Marechaussee",
    "KMC": "Korps Mobiele Colonnes",
    "KNRM": "Koninklijke Nederlandse Reddingsmaatschappij",
    "KR": "Kraanwagen",
    "KWC": "Kustwachtcentrum",
    # L
    "LBB": "Landelijke Bijzondere Bijstand",
    "LBK": "Leiding buiten kantooruren (politie)",
    "LBT": "Landelijk Bijstandsteam Terreurbestrijding",
    "LNV": "Ministerie van Landbouw, Natuurbeheer en Visserij",
    "LOP": "Leidraad Operationele Prestaties",
    "LOTT": "Landelijke Organisatie Trauma Teams",
    "LP": "Logistiek Piket (BRW)",
    "LVBT": "Landelijk Verkeersbijstandsteam (KLPD)",
    # M
    "MAA": "Medical Air Assistance (traumaheli's ANWB)",
    "MB": "Middelbrand",
    "MBV": "Minimaal beveiligd vervoer",
    "MCU": "Mobiele Communicatie / Commando Unit",
    "MDO": "Multidisciplinair Overleg",
    "MDT": "Mobiele Dataterminal",
    "ME": "Mobiele Eenheid (politie)",
    "MF": "Multifunctionele Haakarmbak (BRW)",
    "MIVD": "Militaire Inlichtingen- en Veiligheidsdienst",
    "MK": "Meldkamer",
    "ML": "Medisch leider",
    "MMK": "Mobiele meldkamer (van politie)",
    "MMT": "Mobiel medisch team (trauma team)",
    "MMZ": "Medewerker Maatschappelijke Zorg",
    "MOB": "Medische Ondersteuning Brandweer / Mobilofoon",
    "MPT": "Maritime Police Team",
    "MS": "Motorspuitaanhanger (BRW)",
    "MUG": "Medische Urgentiegroep",
    "MUH": "Medische Urgentie Heli (traumahelikopter)",
    # N
    "NATRES": "Nationale Reserve",
    "NBDC": "Nationaal Brandweer Documentatie Centrum",
    "NB": "Nader bericht",
    "NCC": "Nationaal Coördinatiecentrum",
    "NFI": "Nederlands Forensisch Instituut",
    "NRK": "Nederlandse Rode Kruis",
    "NS": "Nederlandse Spoorwegen",
    "NVBR": "Nederlandse Vereniging voor Brandweerzorg en Rampenbestrijding",
    # O
    "OBP": "Operationeel basisplan",
    "OC": "Operationeel Coördinator",
    "OD": "Officier van Dienst",
    "OGS": "Ongevalsbestrijding gevaarlijke stoffen",
    "OHD": "Overheidshulpdiensten",
    "OL": "Operationeel leider",
    "OM": "Openbaar Ministerie",
    "OMS": "Openbaar Meldsysteem",
    "OPCDT": "Operationeel commandant",
    "OPS": "Opsporingssysteem (politie)",
    "OSC": "On Scene Commander",
    "OSP": "Ondersteuningspeloton",
    "OST": "Ondersteuning",
    "OTH": "Ontsmettings Haakarmbak",
    "OT": "Observatieteam (politie)",
    "OvDB": "Officier van dienst Brandweer",
    "OvDG": "Officier van dienst Geneeskundig",
    "OvD": "Officier van Dienst",
    "OvDP": "Officier van dienst Politie",
    "OvDRail": "Officier van dienst ProRail",
    "OvJ": "Officier van Justitie",
    # P
    "P2000": "Pagersysteem",
    "PA": "Personenauto",
    "PBM": "Persoonlijke Beschermingsmiddelen",
    "PB": "Poederblusvoertuig",
    "PCC": "Provinciaal coördinatie centrum",
    "PC": "Pelotonscommandant",
    "PD": "Plaats Delict",
    "PG": "Procureur Generaal",
    "PID": "Politie Informatiedienst",
    "PI": "Plaats Incident",
    "PIT": "Surveillancedienst politie",
    "PLD": "Politie Luchtvaartdienst (KLPD)",
    "PMC": "Provinciaal Militair Commando",
    "PMK": "Politie Meldkamer",
    "PM": "Personeel / Materieelwagen",
    "POL": "Politie",
    "PORTO": "Portofoon",
    "PRS": "Provinciale rampenstaf",
    "PT": "Portofoon",
    "PVD": "Politie Verbindingsdienst",
    "PV": "Proces Verbaal",
    # R
    "RAC": "Regionale alarmcentrale",
    "RAG": "Recherche Assistentiegroep",
    "RAV": "Regionale ambulancevoorziening",
    "RBO": "Rampenbestrijdings-organisatie",
    "RB": "Reddingsbrigade",
    "RBT": "Regionaal beleidsteam",
    "RBV": "Regulier beveiligd vervoer",
    "RCC": "Regionaal coördinatiecentrum",
    "RCDT": "Regionaal Commandant (BRW)",
    "RCvD": "Regionaal commandant van dienst",
    "RDW": "Rijksdienst Wegverkeer",
    "REC": "Regionale Expertisecentra",
    "RGF": "Regionale Geneeskundige Functionaris",
    "RGO": "Rampenbestrijding en Grootschalig Optreden",
    "RHH": "Reddingshonden Hulpdienst Holland",
    "RIVM": "Rijksinstituut voor Volksgezondheid en Milieuhygiëne",
    "RIV": "Rapid Intervention Vehicle",
    "RIT": "Rampen identificatie team (politie)",
    "RN": "Reddingsbrigades Nederland",
    "ROC": "Regionaal Operationeel Centrum",
    "ROGS": "Regionale deskundige Ongevalsbestrijding Gevaarlijke Stoffen",
    "ROT": "Regionaal Ondersteuningsteam",
    "RT": "Rampterrein",
    "RVD": "Rijksvoorlichtingsdienst",
    "RVHT": "Regionaal Verkeers-handhavingsteam (politie)",
    "RVI": "Rijksverkeersinspectie",
    "RWS": "Rijkswaterstaat",
    # S
    "SAR": "Search And Rescue",
    "SBB": "Staatsbosbeheer",
    "SB": "Schuimblusvoertuig",
    "SEH": "Spoedeisende Hulp",
    "SIGMA": "Snel Inzetbare Groep ter Medische Assistentie",
    "SITRAP": "Situatie-rapport",
    "SL": "Slangenwagen",
    "SOB": "Stafofficier Operatiën Brandweer",
    "SO": "Stafofficier",
    "SPB": "Schuim- / Poederbluswagen (BRW)",
    "SWAB": "Samen Werken Aan Bereikbaarheid (spitsteams politie)",
    "SZW": "Ministerie van Sociale Zaken en Werkgelegenheid",
    # T
    "TAS": "Tankautospuit",
    "TAWA": "Tankwagen (BRW)",
    "TEV": "Team Explosieven Verkenning",
    "THV": "Technische Hulpverlening",
    "THW": "Technisches Hilfswerk",
    "TIS": "Trein incident scenario",
    "TML": "Toegevoegd medisch leider",
    "TNO": "Toegepast Natuurwetenschappelijk Onderzoek",
    "TOD": "Technische Ongevallendienst",
    "TR": "Technische Recherche",
    "TS": "Tankautospuit",
    "TW": "Tankwagen",
    # U
    "UGS": "Uitgangsstelling",
    "USAR": "Urban Search and Rescue (team)",
    # V
    "VAG": "Vaardigheden Aanhoudingen in Groepsverband (politie)",
    "VBB": "Vereniging Belangstellenden Brandweerwezen",
    "VBS": "Nederlandse Vereniging van Bergingsspecialisten",
    "VC": "Verbinding- Commandovoertuig",
    "VCK": "Verkeers Commando / Controle Kamer",
    "VCU": "Verbindings Commando Unit",
    "VD": "Verbindingsdeskundige van Dienst (BRW)",
    "VG": "Verzamelplaats gewonden",
    "VHD": "Verzekeraars Hulpdienst",
    "VOA": "Verkeersongevallen Analyse",
    "VPK": "Verpleegkundige",
    "VPO": "Verlaten Plaats Ongeval",
    "VVD": "Voorlichter van dienst",
    "VW": "Vrachtwagen",
    # W
    "WA": "Waarschuwingsadres",
    "WC": "Winkelcentrum",
    "WGHOR": "Wet Geneeskundige Hulpverlening bij Ongevallen en Rampen",
    "WO": "Waterongevallenwagen",
    "WRB": "Wassenaarse Reddingsbrigade",
    "WRZO": "Wet rampen en zware ongevallen",
    "WVD": "Waarschuwings- en Verkenningsdiensten",
    "WvS": "Wetboek van Strafrecht",
    # P2000 specific
    "PRIO": "Prioriteit",
    "P1": "Prioriteit 1 (spoed)",
    "P2": "Prioriteit 2 (dringend)",
    "P3": "Prioriteit 3 (niet urgent)",
    "A1": "Ambulance met spoed",
    "A2": "Ambulance zonder spoed",
    "B1": "Brandweer met spoed",
    "B2": "Brandweer zonder spoed",
    "DIA": "Directe Inzet Ambulance",
    "VWS": "Voorwaardescheppend (ambulance staat tijdelijk paraat op vaste opstelplaats)",
    "SIV": "Snel Interventie Voertuig",
    "OVD-B": "Officier van Dienst Brandweer",
    "OVD-G": "Officier van Dienst Geneeskundig",
    "OVD-P": "Officier van Dienst Politie",
    "TS-HV": "Tankautospuit Hulpverlening",
    "AL-42": "Autoladder 42 meter",
    "AL-36": "Autoladder 36 meter",
    "AL-32": "Autoladder 32 meter",
    "HW-36": "Hoogwerker 36 meter",
    "HW-24": "Hoogwerker 24 meter",
    "PM-90": "Personeels/Materieel wagen 90",
    "WTS": "Watertransportsysteem",
    "SL-4": "Slangenwagen 4",
    "SL-6": "Slangenwagen 6",
    "VZH": "Verzorgingshaakarmbak",
    "LHH": "Luchthaakarmbak",
    "CHH": "Commandohaakarmbak",
    # Meldkamer gespreksgroepen (B = Brandweer + meldkamer location;
    # the -NN suffix is the incident channel, matched via prefix)
    # Source: https://nl.wikipedia.org/wiki/P2000_(netwerk)
    "BDH": "Brandweer Den Haag (gespreksgroep)",
    "BNN": "Brandweer Noord-Nederland (gespreksgroep)",
    "BON": "Brandweer Oost-Nederland (gespreksgroep)",
    "BNH": "Brandweer Noord-Holland (gespreksgroep)",
    "BLB": "Brandweer Limburg (gespreksgroep)",
    "BOB": "Brandweer Oost-Brabant (gespreksgroep)",
    "BAD": "Brandweer Amsterdam-Amstelland (gespreksgroep)",
    "BMD": "Brandweer Midden-Nederland (gespreksgroep)",
    "BRT": "Brandweer Rotterdam (gespreksgroep)",
    "BZB": "Brandweer Zeeland (gespreksgroep)",
    # Ambulance dienstposten (DP4 = Delft, regio Haaglanden)
    "DP": "Dienstpost (ambulancepost)",
}

# Some P2000 priority codes are reused across disciplines with unrelated
# meanings - B1/B2 mean "Brandweer uitruk" for fire but "Ambulance besteld
# vervoer" (planned, non-urgent transport) for ambulance, since both
# services independently adopted the same letter+digit naming scheme.
# ABBREVIATIONS above only holds one (fire) meaning per code, so this table
# overrides it when the message's resolved discipline says otherwise.
# Keyed by (code, lowercase discipline substring to match).
#
# Sources (2026-08-28): iserbrand.nl/p2000-codes ("B: Routine / besteld
# vervoer. Planbaar, ingezet wanneer er ruimte is") and 112hub.nl
# ("B1: Betreft een hoogcomplexe zorgvraag" / "B2: Betreft een
# middencomplexe of laagcomplexe zorgvraag") - unlike fire's B1/B2, neither
# ambulance code means "met/geen spoed": both are non-urgent by definition,
# distinguished by care complexity instead.
DISCIPLINE_ABBREVIATION_OVERRIDES: dict[tuple[str, str], str] = {
    ("B1", "ambulance"): "Ambulance besteld vervoer, hoogcomplexe zorgvraag",
    ("B2", "ambulance"): "Ambulance besteld vervoer, midden- of laagcomplexe zorgvraag",
}


def import_abbreviations(database) -> int:
    """Import all abbreviations to database. Returns count imported."""
    abbrevs = [{"abbreviation": k, "full_text": v} for k, v in ABBREVIATIONS.items()]
    count = database.import_abbreviations(abbrevs)
    logger.info(f"Imported {count} abbreviations")
    return count
