"""City abbreviations for Dutch cities.

This file was auto-generated from p2000.sqlite3 database.
Contains 2509 city name to abbreviation mappings.
"""

CITY_ABBREVIATIONS = {
    "'s Gravenmoer": "SGRAVM",
    "'s-Graveland": "SGRAVL",
    "'s-Gravendeel": "SGRAVD",
    "'s-Gravenhage": "SGRAVH",
    "'s-Gravenpolder": "SGRAVP",
    "'s-Gravenzande": "SGRAVZ",
    "'s-Heer Abtskerke": "SHEEAB",
    "'s-Heer Arendskerke": "SHEEAR",
    "'s-Heer Hendrikskinderen": "SHEEHK",
    "'s-Heerenberg": "SHEEBG",
    "'s-Heerenbroek": "SHEEBK",
    "'s-Heerenhoek": "SHEEHO",
    "'s-Hertogenbosch": "SHERTO",
    "'t Goy": "TGOY",
    "'t Haantje": "THAANT",
    "'t Harde": "THARDE",
    "'t Loo Oldebroek": "TLOOOL",
    "'t Veld": "TVELD",
    "'t Waar": "TWAAR",
    "'t Zand": "TZAND",
    "'t Zandt": "TZANDT",
    "1e Exloermond": "1EXLMD",
    "2e Exloermond": "2EXLMD",
    "2e Valthermond": "2VLTMD",
    "Aadorp": "AADORP",
    "Aagtekerke": "AAGTKK",
    "Aalden": "AALDEN",
    "Aalsmeer": "AALSMR",
    "Aalsmeerderbrug": "AALSMB",
    "Aalst": "AALST",
    "Aalsum": "AALSUM",
    "Aalten": "AALTEN",
    "Aardenburg": "AARDBG",
    "Aarlanderveen": "AARLVN",
    "Aarle-Rixtel": "AARLRL",
    "Aartswoud": "AARTSW",
    "Abbega": "ABBEGA",
    "Abbekerk": "ABBKRK",
    "Abbenbroek": "ABBBRK",
    "Abbenes": "ABBNES",
    "Abcoude": "ABCOUD",
    "Achlum": "ACHLUM",
    "Achterveld GE": "ACHTGE",
    "Achterveld UT": "ACHTUT",
    "Achthuizen": "ACHTHZ",
    "Achtmaal": "ACHTML",
    "Acquoy": "ACQUOY",
    "Adorp": "ADORP",
    "Aduard": "ADUARD",
    "Aerdenhout": "AERDHT",
    "Aerdt": "AERDT",
    "Afferden GE": "AFFDGE",
    "Afferden L": "AFFDLI",
    "Agelo": "AGELO",
    "Akersloot": "AKERSL",
    "Akkrum": "AKKRUM",
    "Akmarijp": "AKMRP",
    "Albergen": "ALBRGN",
    "Alblasserdam": "ALBLDM",
    "Alde Leie": "ALDLEI",
    "Aldeboarn": "ALDBRN",
    "Aldtsjerk": "ALDTSK",
    "Alem": "ALEM",
    "Alkmaar": "ALKMR",
    "Allingawier": "ALLGWR",
    "Almelo": "ALMELO",
    "Almen": "ALMEN",
    "Almere": "ALMERE",
    "Almkerk": "ALMKRK",
    "Alphen GE": "ALPHGE",
    "Alphen NB": "ALPHNB",
    "Alphen aan den Rijn": "ALPHRN",
    "Alteveer De Wolden": "ALTVDW",
    "Alteveer GR": "ALTVGR",
    "Alteveer Gem Zuidwolde": "ALTVZW",
    "Alteveer Noordenveld": "ALTVNV",
    "Alteveer gem Hoogeveen": "ALTVHV",
    "Altforst": "ALTFST",
    "Ambt Delden": "AMBTDD",
    "Ameide": "AMEIDE",
    "Amen": "AMEN",
    "America": "AMERCA",
    "Amerongen": "AMERGN",
    "Amersfoort": "AMERSF",
    "Ammerstol": "AMMSTL",
    "Ammerzoden": "AMMZDN",
    "Amstelhoek": "AMSTHK",
    "Amstelveen": "AMVEEN",
    "Amstenrade": "AMSTRD",
    "Amsterdam": "AMSDAM",
    "Amsterdam Zuidoost": "AMSZO",
    "Amsterdam-Duivendrecht": "AMSDVD",
    "Andel": "ANDEL",
    "Andelst": "ANDLST",
    "Anderen": "ANDERN",
    "Andijk": "ANDIJK",
    "Ane": "ANE",
    "Anerveen": "ANERVN",
    "Anevelde": "ANEVLD",
    "Angeren": "ANGERN",
    "Angerlo": "ANGRLO",
    "Anjum": "ANJUM",
    "Ankeveen": "ANKVN",
    "Anloo": "ANLOO",
    "Anna Paulowna": "ANNPWN",
    "Annen": "ANNEN",
    "Annerveenschekanaal": "ANNVKL",
    "Ansen": "ANSNDW",
    "Ansen Westerveld": "ANSNWV",
    "Apeldoorn": "APELDN",
    "Appelscha": "APPSCH",
    "Appeltern": "APPTRN",
    "Appingedam": "APPDAM",
    "Arcen": "ARCEN",
    "Arkel": "ARKEL",
    "Arnemuiden": "ARNEMD",
    "Arnhem": "ARNHEM",
    "Arrien": "ARRIEN",
    "Arum": "ARUM",
    "Asch": "ASCH",
    "Asperen": "ASPERN",
    "Assen": "ASSEN",
    "Assendelft": "ASSDLF",
    "Asten": "ASTEN",
    "Augsbuurt": "AUGBRT",
    "Augustinusga": "AUGTSG",
    "Austerlitz": "AUSLTZ",
    "Avenhorn": "AVENHN",
    "Axel": "AXEL",
    "Azewijn": "AZEWN",
    "Baaiduinen": "BAAIDN",
    "Baaium": "BAAIUM",
    "Baak": "BAAK",
    "Baambrugge": "BAAMBG",
    "Baard": "BAARD",
    "Baarland": "BAARLD",
    "Baarle-Nassau": "BAARNS",
    "Baarlo LI": "BAARLI",
    "Baarlo OV": "BAAROV",
    "Baarn": "BAARN",
    "Baars": "BAARS",
    "Babberich": "BABRCH",
    "Babylonienbroek": "BABBRK",
    "Bad Nieuweschans": "BADNIE",
    "Badhoevedorp": "BADHDP",
    "Baexem": "BAEXEM",
    "Baflo": "BAFLO",
    "Bakel": "BAKEL",
    "Bakhuizen": "BAKHZN",
    "Bakkeveen": "BAKKVN",
    "Balgoij": "BALGOJ",
    "Balinge": "BALING",
    "Balk": "BALK",
    "Balkbrug": "BALKBG",
    "Balloerveld": "BALLVD",
    "Balloo": "BALLOO",
    "Ballum": "BALLUM",
    "Baneheide": "BANEHD",
    "Banholt": "BANHLT",
    "Bant": "BANT",
    "Bantega": "BANTGA",
    "Barchem": "BARCHM",
    "Barendrecht": "BARDRT",
    "Barger-Compascuum": "BARGCO",
    "Barneveld": "BARNVD",
    "Barsingerhorn": "BARSHN",
    "Basse": "BASSE",
    "Batenburg": "BATBRG",
    "Bathmen": "BATHMN",
    "Bavel": "BAVELB",
    "Bavel AC": "BAVELA",
    "Bears": "BEARS",
    "Bedum": "BEDUM",
    "Beegden": "BEEGDN",
    "Beek LI": "BEEKLI",
    "Beek Montferland": "BEEKMO",
    "Beek Ubbergen": "BEEKGB",
    "Beek en Donk": "BEEKDK",
    "Beekbergen": "BEEKBG",
    "Beemte Broekland": "BEEMBR",
    "Beers NB": "BEERS",
    "Beerta": "BEERTA",
    "Beerze": "BEERZE",
    "Beerzerveld": "BEERVD",
    "Beesd": "BEESD",
    "Beesel": "BEESEL",
    "Beets": "BEETS",
    "Beetsterzwaag": "BEETZG",
    "Beilen": "BEILEN",
    "Beinsdorp": "BEINDP",
    "Belfeld": "BELFLD",
    "Bellingwolde": "BELWLD",
    "Belt-Schutsloot": "BELTSS",
    "Beltrum": "BELTRM",
    "Bemelen": "BEMELN",
    "Bemmel": "BEMMEL",
    "Beneden-Leeuwen": "BENLWN",
    "Bennebroek": "BENNBK",
    "Bennekom": "BENNKM",
    "Benneveld": "BENNVD",
    "Benningbroek": "BENNIB",
    "Benschop": "BENSCH",
    "Bentelo": "BENTLO",
    "Benthuizen": "BENTHZ",
    "Bentveld": "BENTVD",
    "Berg en Dal": "BERGDL",
    "Berg en Terblijt": "BERGTB",
    "Bergambacht": "BERGAB",
    "Bergeijk": "BERGEK",
    "Bergen (NH)": "BERGNH",
    "Bergen L": "BERGLI",
    "Bergen aan Zee": "BERGAZ",
    "Bergen op Zoom": "BERGZM",
    "Bergentheim": "BERGTH",
    "Bergharen": "BERGHN",
    "Berghem": "BERGHM",
    "Bergschenhoek": "BERGHK",
    "Beringe": "BERING",
    "Berkel en Rodenrijs": "BERKRR",
    "Berkel-Enschot": "BERKES",
    "Berkenwoude": "BERKWD",
    "Berkhout": "BERKHT",
    "Berlicum": "BERLCM",
    "Berltsum": "BERLTS",
    "Bern": "BERN",
    "Best": "BEST",
    "Beugen": "BEUGEN",
    "Beuningen Gld": "BEUNGE",
    "Beuningen OV": "BEUNOV",
    "Beusichem": "BEUSCM",
    "Beutenaken": "BEUTAK",
    "Beverwijk": "BEVERW",
    "Biddinghuizen": "BIDDHZ",
    "Bierum": "BIERUM",
    "Biervliet": "BIERTN",
    "Biervliet Sluis": "BIERSL",
    "Biest-Houtakker": "BIESTH",
    "Biezenmortel": "BIEZML",
    "Biggekerke": "BIGGKK",
    "Bilthoven": "BILTHV",
    "Bingelrade": "BINGRD",
    "Bitgum": "BITGUM",
    "Bitgummole": "BITGMM",
    "Bladel": "BLADEL",
    "Blankenham": "BLANKH",
    "Blaricum": "BLARCM",
    "Blauwestad": "BLAUWS",
    "Blauwhuis": "BLAUWH",
    "Bleiswijk": "BLEISW",
    "Blesdijke": "BLESDK",
    "Bleskensgraaf ca": "BLESGF",
    "Blessum": "BLESSM",
    "Blije": "BLIJE",
    "Blijham": "BLIJHM",
    "Blitterswijck": "BLITWK",
    "Bloemendaal": "BLOEMD",
    "Blokker": "BLOKKR",
    "Blokzijl": "BLOKZL",
    "Boazum": "BOAZUM",
    "Bocholtz": "BOCHLZ",
    "Bodegraven": "BODEGR",
    "Boekel": "BOEKEL",
    "Boelenslaan": "BOELSL",
    "Boer": "BOER",
    "Boerakker Leek": "BOERAL",
    "Boerakker Marum": "BOERAM",
    "Boesingheliede": "BOESLD",
    "Boijl": "BOIJL",
    "Boksum": "BOKSUM",
    "Bolsward": "BOLSWD",
    "Bontebok": "BONTBK",
    "Boornbergum": "BOORNB",
    "Boornzwaag": "BOORNZ",
    "Borculo": "BORCLO",
    "Borger": "BORGER",
    "Borgercompagnie Menterw.": "BORGCM",
    "Borgercompagnie Veendam": "BORGCV",
    "Borgsweer": "BORGSW",
    "Born": "BORN",
    "Borne": "BORNE",
    "Bornerbroek": "BORNBK",
    "Bornwird": "BORNWD",
    "Borssele": "BORSLE",
    "Bosch en Duin": "BOSCHD",
    "Boschoord": "BOSCHO",
    "Boskoop": "BOSKP",
    "Bosschenhoofd": "BOSSNH",
    "Botlek Rotterdam": "BOTLEK",
    "Bourtange": "BOURTG",
    "Boven-Leeuwen": "BOVLWN",
    "Bovenkarspel": "BOVNKS",
    "Bovensmilde": "BOVSMD",
    "Boxmeer": "BOXMR",
    "Boxtel": "BOXTEL",
    "Braamt": "BRAAMT",
    "Brakel": "BRAKEL",
    "Brandwijk": "BRANDW",
    "Brantgum": "BRANTG",
    "Breda": "BREDA",
    "Bredevoort": "BREDVT",
    "Breedenbroek": "BREEDB",
    "Breezand": "BREEZA",
    "Breezanddijk": "BREEZD",
    "Breskens": "BRESKS",
    "Breukelen": "BREUKL",
    "Breukeleveen": "BREUKV",
    "Brielle": "BRIELL",
    "Briltil": "BRILTL",
    "Britsum": "BRITSM",
    "Britswert": "BRITSW",
    "Broek": "BROEK",
    "Broek in Waterland": "BROEKW",
    "Broek op Langedijk": "BROEKO",
    "Broekhuizen Dr": "BROEDR",
    "Broekhuizen LI": "BROELI",
    "Broekhuizenvorst": "BROEKV",
    "Broekland": "BROEKL",
    "Broeksterwald": "BROEKS",
    "Bronkhorst": "BRONKH",
    "Bronneger": "BRONNV",
    "Bronnegerveen": "BRONNH",
    "Brouwershaven": "BROUWH",
    "Bruchem": "BRUCHM",
    "Brucht": "BRUCHT",
    "Bruchterveld": "BRUCHV",
    "Bruinehaar": "BRUINH",
    "Bruinisse": "BRUINN",
    "Brummen": "BRUMMN",
    "Brunssum": "BRUNSS",
    "Bruntinge": "BRUNTG",
    "Buchten": "BUCHTN",
    "Budel": "BUDEL",
    "Budel-Dorplein": "BUDELD",
    "Budel-Schoot": "BUDELS",
    "Buggenum": "BUGGNM",
    "Buinen": "BUINEN",
    "Buinerveen": "BUINVN",
    "Buitenkaag": "BUITKG",
    "Buitenpost": "BUITPT",
    "Bunde": "BUNDE",
    "Bunne": "BUNNE",
    "Bunnik": "BUNNIK",
    "Bunschoten-Spakenburg": "BUNSPK",
    "Burdaard": "BURDRD",
    "Buren Ameland": "BURNFR",
    "Buren GE": "BURNGE",
    "Burgerbrug": "BURGBG",
    "Burgerveen": "BURGVN",
    "Burgh-Haamstede": "BURGHH",
    "Burgum": "BURGUM",
    "Burgwerd": "BURGWD",
    "Burum": "BURUM",
    "Bussum": "BUSSUM",
    "Buurmalsen Buren": "BUURBR",
    "Buurmalsen Geldermalsen": "BUURGM",
    "Cadier en Keer": "CADKR",
    "Cadzand": "CADZND",
    "Callantsoog": "CALLTO",
    "Capelle aan den IJssel": "CAPIJS",
    "Castelre": "CASTLR",
    "Castenray": "CASTRY",
    "Casteren": "CASTRN",
    "Castricum": "CASTRC",
    "Chaam": "CHAAM",
    "Clinge": "CLINGE",
    "Coevorden": "COEVDN",
    "Colijnsplaat": "COLPLT",
    "Collendoorn": "COLLDN",
    "Colmschate": "COLMST",
    "Cornwerd": "CORNWD",
    "Cothen": "COTHEN",
    "Creil": "CREIL",
    "Cromvoirt": "CROMVT",
    "Cruquius": "CRUQS",
    "Cuijk": "CUIJK",
    "Culemborg": "CULMBG",
    "Daarle": "DAARLE",
    "Daarlerveen": "DAARLV",
    "Dalem": "DALEM",
    "Dalen": "DALEN",
    "Dalerpeel": "DALERP",
    "Dalerveen": "DALERV",
    "Dalfsen": "DALFSN",
    "Dalmsholte": "DALMSH",
    "Damwald": "DAMWLD",
    "Darp": "DARP",
    "De Bilt": "DEBILT",
    "De Blesse": "DEBLES",
    "De Bult": "DEBULT",
    "De Cocksdorp": "DECOCK",
    "De Falom": "DEFALM",
    "De Glind": "DEGLIN",
    "De Goorn": "DEGOOR",
    "De Groeve": "DEGROE",
    "De Heen": "DEHEEN",
    "De Heurne": "DEHEUR",
    "De Hoeve": "DEHVE",
    "De Kiel": "DEKIEL",
    "De Klomp": "DEKLOM",
    "De Knipe": "DEKNIP",
    "De Koog": "DEKOOG",
    "De Krim": "DEKRIM",
    "De Kwakel": "DEKWAK",
    "De Lier": "DELIER",
    "De Meern": "DEMEER",
    "De Moer": "DEMOER",
    "De Mortel": "DEMORT",
    "De Pol": "DEPOL",
    "De Punt": "DEPUNT",
    "De Rijp": "DERIJP",
    "De Rips": "DERIPS",
    "De Schiphorst": "DESCHI",
    "De Steeg": "DESTEE",
    "De Tike": "DETIKE",
    "De Veenhoop": "DEVEEN",
    "De Waal": "DEWAAL",
    "De Weere": "DEWEER",
    "De Westereen": "DEWEST",
    "De Wilgen": "DEWILG",
    "De Wilp": "DEWILP",
    "De Zilk": "DEZILK",
    "Dearsum": "DEARSM",
    "Dedemsvaart": "DEDEMV",
    "Dedgum": "DEDGUM",
    "Deelen": "DEELEN",
    "Deest": "DEEST",
    "Deil": "DEIL",
    "Deinum": "DEINUM",
    "Delden": "DELDEN",
    "Delfgauw": "DELFGW",
    "Delfstrahuizen": "DELFHZ",
    "Delft": "DELFT",
    "Delfzijl": "DELFZL",
    "Delwijnen": "DELWNN",
    "Demen": "DEMEN",
    "Den Andel": "DENAND",
    "Den Bommel": "DENBOM",
    "Den Burg": "DENBUG",
    "Den Dolder": "DENDOL",
    "Den Dungen": "DENDUN",
    "Den Ham GR": "DENHGR",
    "Den Ham OV": "DENHOV",
    "Den Helder": "DENHEL",
    "Den Hoorn": "DENHNH",
    "Den Hoorn ZH": "DENHZH",
    "Den Horn": "DENHOR",
    "Den Hout": "DENHOU",
    "Den Ilp": "DENILP",
    "Den Oever": "DENOEV",
    "Den Velde": "DENVEL",
    "Denekamp": "DENEKP",
    "Deurne": "DEURNE",
    "Deurningen Dinkelland": "DEURDI",
    "Deurningen Oldenzaal": "DEUROL",
    "Deursen-Dennenburg": "DEURSD",
    "Deurze": "DEURZE",
    "Deventer": "DEVENT",
    "Didam": "DIDAM",
    "Dieden": "DIEDEN",
    "Diemen": "DIEMEN",
    "Diepenheim": "DIEPHM",
    "Diepenveen": "DIEPVN",
    "Dieren": "DIEREN",
    "Diessen": "DIESSN",
    "Diever": "DIEVER",
    "Dieverbrug": "DIEVBG",
    "Diffelen": "DIFFLN",
    "Dijken": "DIJKEN",
    "Dinteloord": "DINTLD",
    "Dinxperlo": "DINXPL",
    "Diphoorn": "DIPSHN",
    "Dirkshorn": "DIRKHN",
    "Dirksland": "DIRKLD",
    "Dodewaard": "DODEWD",
    "Doenrade": "DOENRD",
    "Doesburg": "DOESBG",
    "Doetinchem": "DOETCH",
    "Doeveren": "DOEVRN",
    "Doezum": "DOEZUM",
    "Dokkum": "DOKKUM",
    "Doldersum": "DOLDSM",
    "Domburg": "DOMBRG",
    "Donderen": "DONDRN",
    "Dongen": "DONGEN",
    "Dongjum": "DONGJM",
    "Doniaga": "DONIAG",
    "Donkerbroek": "DONKBR",
    "Doorn": "DOORN",
    "Doornenburg": "DOORNB",
    "Doornspijk": "DOORNS",
    "Doorwerth": "DOORWT",
    "Dordrecht": "DORDRT",
    "Dorst": "DORST",
    "Drachten": "DRACHT",
    "Drachten-Azeven": "DRACHA",
    "Drachtstercompagnie": "DRACHC",
    "Dreischor": "DREISR",
    "Drempt": "DREMPT",
    "Dreumel": "DREUML",
    "Driebergen-Rijsenburg": "DRIERB",
    "Drieborg": "DRIEBG",
    "Driebruggen": "DRIEBN",
    "Driehuis NH": "DRIEHS",
    "Driehuizen": "DRIEHZ",
    "Driel": "DRIEL",
    "Driewegen": "DRIEWG",
    "Driezum": "DRIEZM",
    "Drijber": "DRIJBR",
    "Drimmelen": "DRIMML",
    "Drogeham": "DROGEH",
    "Drogteropslagen": "DROGTO",
    "Drongelen": "DRONGL",
    "Dronryp": "DRONRP",
    "Dronten": "DRONTN",
    "Drouwen": "DROUWN",
    "Drouwenermond": "DROUMD",
    "Drouwenerveen": "DROUVN",
    "Drunen": "DRUNEN",
    "Druten": "DRUTEN",
    "Duiven": "DUIVEN",
    "Duivendrecht": "DUIVDT",
    "Duizel": "DUIZEL",
    "Dussen": "DUSSEN",
    "Dwingeloo": "DWINGL",
    "Eagum": "EAGUM",
    "Earnewald": "EARNWD",
    "Easterein": "EASTRN",
    "Easterlittens": "EASTLT",
    "Eastermar": "EASTMR",
    "Easterwierrum": "EASTWR",
    "Echt": "ECHT",
    "Echteld": "ECHTLD",
    "Echten Dr": "ECHNDR",
    "Echten Fr": "ECHNFR",
    "Echtenerbrug": "ECHTBG",
    "Eck en Wiel": "ECKWL",
    "Eckelrade": "ECKLRD",
    "Edam": "EDAM",
    "Ede": "EDE",
    "Ederveen": "EDERVN",
    "Ee": "EE",
    "Eede": "EEDE",
    "Eefde": "EEFDE",
    "Eelde": "EELDE",
    "Eelderwolde": "EELDWL",
    "Eemdijk": "EEMDK",
    "Eemnes": "EEMNES",
    "Eemshaven": "EEMSHV",
    "Een": "EEN",
    "Een-West": "EENWST",
    "Eenrum": "EENRUM",
    "Eenum": "EENUM",
    "Eerbeek": "EERBK",
    "Eersel": "EERSEL",
    "Ees": "EES",
    "Eesergroen": "EESGRN",
    "Eeserveen": "EESRVN",
    "Eesterga": "EESTGA",
    "Eesveen": "EESVN",
    "Eethen": "EETHEN",
    "Eext": "EEXT",
    "Eexterveen": "EEXTVN",
    "Eexterveenschekanaal": "EEXTVK",
    "Eexterzandvoort": "EEXTZV",
    "Egchel": "EGCHEL",
    "Egmond aan Zee": "EGMONZ",
    "Egmond aan den Hoef": "EGMONH",
    "Egmond-Binnen": "EGMONB",
    "Eibergen": "EIBERG",
    "Eijsden": "EIJSDN",
    "Eindhoven": "EINDHV",
    "Einighausen": "EINIGH",
    "Ekehaar": "EKEHR",
    "Elahuizen": "ELAHZN",
    "Elburg": "ELBURG",
    "Eldersloo": "ELDERL",
    "Eleveld": "ELEVLD",
    "Elim": "ELIM",
    "Elkenrade": "ELKENR",
    "Ell": "ELL",
    "Ellecom": "ELLECM",
    "Ellemeet": "ELLEMT",
    "Ellertshaar": "ELLEHR",
    "Ellewoutsdijk": "ELLEWD",
    "Elp": "ELP",
    "Elsendorp": "ELSEND",
    "Elshout": "ELSHT",
    "Elsloo Fr": "ELSLFR",
    "Elsloo LI": "ELSLLI",
    "Elspeet": "ELSPT",
    "Elst GE": "ELSTGE",
    "Elst Ut": "ELSTUT",
    "Emmeloord": "EMMELD",
    "Emmen": "EMMEN",
    "Emmer-Compascuum": "EMMERC",
    "Empe": "EMPE",
    "Emst": "EMST",
    "Engwierum": "ENGWRM",
    "Enkhuizen": "ENKHZN",
    "Ens": "ENS",
    "Enschede": "ENSCHD",
    "Enspijk": "ENSPK",
    "Enter": "ENTER",
    "Enumatil": "ENUMTL",
    "Epe": "EPE",
    "Epen": "EPEN",
    "Eppenhuizen": "EPPENH",
    "Epse": "EPSE",
    "Erica": "ERICA",
    "Erichem": "ERICHM",
    "Erlecom": "ERLECM",
    "Erm": "ERM",
    "Ermelo": "ERMELO",
    "Erp": "ERP",
    "Esbeek": "ESBEEK",
    "Esch": "ESCH",
    "Escharen": "ESCHRN",
    "Espel": "ESPEL",
    "Est": "EST",
    "Etten": "ETTEN",
    "Etten-Leur": "ETTENL",
    "Europoort Rotterdam": "EUROPT",
    "Eursinge": "EURSMD",
    "Eursinge De Wolden": "EURSDW",
    "Everdingen": "EVERDG",
    "Evertsoord": "EVRTSO",
    "Ewijk": "EWIJK",
    "Exloerveen": "EXLRVN",
    "Exloo": "EXLOO",
    "Exmorra": "EXMORR",
    "Eygelshoven": "EYGLHV",
    "Eys": "EYS",
    "Ezinge": "EZINGE",
    "Farmsum": "FARMSM",
    "Feanwalden": "FEANWD",
    "Feerwerd": "FEERWD",
    "Feinsum": "FEINSM",
    "Ferwert": "FERWRT",
    "Ferwoude": "FERWDE",
    "Fijnaart": "FIJNRT",
    "Finsterwolde": "FINSWL",
    "Firdgum": "FIRDGM",
    "Fleringen": "FLERNG",
    "Fluitenberg": "FLUITB",
    "Fochteloo": "FOCHTL",
    "Follega": "FOLLGA",
    "Folsgare": "FOLSGR",
    "Formerum": "FORMRM",
    "Foudgum": "FOUDGM",
    "Foxhol": "FOXHOL",
    "Foxwolde": "FOXWLD",
    "Franeker": "FRANKR",
    "Frederiksoord": "FREDKO",
    "Friens": "FRIENS",
    "Frieschepalen": "FRIEPL",
    "Froombosch": "FROOMB",
    "Gaanderen": "GAANDR",
    "Gaast": "GAAST",
    "Gaastmeer": "GAASTM",
    "Galder": "GALDER",
    "Gameren": "GAMERN",
    "Gapinge": "GAPING",
    "Garderen": "GARDRN",
    "Garmerwolde": "GARMWD",
    "Garminge": "GARMNG",
    "Garnwerd": "GARNWD",
    "Garrelsweer": "GARRLW",
    "Garsthuizen": "GARSTH",
    "Garyp": "GARYP",
    "Gassel": "GASSEL",
    "Gasselte": "GASLTE",
    "Gasselternijveen": "GASNVN",
    "Gasselternijveenschemond": "GASNVM",
    "Gastel": "GASTEL",
    "Gasteren": "GASTRN",
    "Gauw": "GAUW",
    "Geelbroek": "GEELBR",
    "Geerdijk": "GEERDK",
    "Geersdijk": "GEERSD",
    "Geertruidenberg": "GEERTB",
    "Geervliet": "GEERVL",
    "Gees": "GEES",
    "Geesbrug": "GEESBG",
    "Geesteren GE": "GEESGE",
    "Geesteren OV": "GEESOV",
    "Geeuwenbrug": "GEEUWB",
    "Geffen": "GEFFEN",
    "Geijsteren": "GEIJST",
    "Geldermalsen": "GELDML",
    "Gelderswoude": "GELDWD",
    "Geldrop": "GELDRP",
    "Geleen": "GELEEN",
    "Gellicum": "GELLCM",
    "Gelselaar": "GELSLR",
    "Gemert": "GEMERT",
    "Gemonde": "GEMOND",
    "Genderen": "GENDRN",
    "Gendringen": "GENDRG",
    "Gendt": "GENDT",
    "Genemuiden": "GENEMD",
    "Gennep": "GENNEP",
    "Gerkesklooster": "GERKKL",
    "Gersloot": "GERSLT",
    "Geulle": "GEULLE",
    "Giesbeek": "GIESBK",
    "Giessen": "GIESSN",
    "Giessenburg": "GIESBG",
    "Gieten": "GIETEN",
    "Gieterveen": "GIETVN",
    "Giethmen": "GIETNM",
    "Giethoorn": "GIETHN",
    "Gilze": "GILZE",
    "Ginnum": "GINNUM",
    "Glane": "GLANE",
    "Glimmen": "GLIMMN",
    "Godlinze": "GODLNZ",
    "Goedereede": "GOEDRD",
    "Goenga": "GOENGA",
    "Goengahuizen": "GOENHZ",
    "Goes": "GOES",
    "Goingarijp": "GOINGR",
    "Goirle": "GOIRLE",
    "Goor": "GOOR",
    "Gorinchem": "GORCHM",
    "Gorredijk": "GORRDK",
    "Gorssel": "GORSSL",
    "Gouda": "GOUDA",
    "Gouderak": "GOUDRK",
    "Goudriaan": "GOUDRN",
    "Goudswaard": "GOUDWD",
    "Goutum": "GOUTUM",
    "Graauw": "GRAAUW",
    "Grafhorst": "GRAFHT",
    "Graft": "GRAFT",
    "Gramsbergen": "GRAMSB",
    "Grashoek": "GRASHK",
    "Grathem": "GRATHM",
    "Grave": "GRAVE",
    "Greonterp": "GREONT",
    "Grevenbicht": "GREVBT",
    "Griendtsveen": "GRIENV",
    "Grijpskerk": "GRIJPK",
    "Grijpskerke": "GRIJKK",
    "Groede": "GROEDE",
    "Groenekan": "GROENK",
    "Groeningen": "GROENG",
    "Groenlo": "GROENL",
    "Groesbeek": "GROESB",
    "Groessen": "GROESS",
    "Groet": "GROET",
    "Grolloo": "GROLLO",
    "Groningen": "GRONGN",
    "Gronsveld": "GRONSV",
    "Groot-Ammers": "GROOTA",
    "Grootebroek": "GROOTB",
    "Grootegast": "GROOTG",
    "Grootschermer": "GROOTS",
    "Grou": "GROU",
    "Grubbenvorst": "GRUBVS",
    "Gulpen": "GULPEN",
    "Guttecoven": "GUTTEC",
    "Gytsjerk": "GYTSJK",
    "Haaften": "HAAFTN",
    "Haaksbergen": "HAAKSB",
    "Haalderen": "HAALDR",
    "Haaren": "HAAREN",
    "Haarle Hellendoorn": "HAARLH",
    "Haarle Tubbergen": "HAARLT",
    "Haarlem": "HAARLM",
    "Haarlemmerliede": "HAARLL",
    "Haarlo": "HAARLO",
    "Haarsteeg": "HAARST",
    "Haarzuilens": "HAARZL",
    "Haastrecht": "HAASTR",
    "Haelen": "HAELEN",
    "Hagestein": "HAGEST",
    "Haghorst": "HAGHST",
    "Haler": "HALER",
    "Halfweg": "HALFWG",
    "Hall": "HALL",
    "Halle": "HALLE",
    "Hallum": "HALLUM",
    "Halsteren": "HALSTR",
    "Handel": "HANDEL",
    "Hank": "HANK",
    "Hansweert": "HANSWT",
    "Hantum": "HANTUM",
    "Hantumeruitburen": "HANTBR",
    "Hantumhuizen": "HANTHZ",
    "Hapert": "HAPERT",
    "Haps": "HAPS",
    "Harbrinkhoek": "HARBHK",
    "Hardenberg": "HARDBG",
    "Harderwijk": "HARDWK",
    "Hardinxveld-Giessendam": "HARDGD",
    "Haren Gn": "HARNGR",
    "Haren Oss": "HARNNB",
    "Harfsen": "HARFSN",
    "Harich": "HARICH",
    "Haringhuizen": "HARIHZ",
    "Harkema": "HARKMA",
    "Harkstede": "HARKST",
    "Harkstede GN": "HARKGN",
    "Harlingen": "HARLGN",
    "Harmelen": "HARMLN",
    "Harreveld": "HARRVD",
    "Harskamp": "HARSKP",
    "Hartwerd": "HARTWD",
    "Haskerdijken": "HASTDK",
    "Haskerhorne": "HASKHN",
    "Hasselt": "HASSLT",
    "Hattem": "HATTEM",
    "Hattemerbroek": "HATTBR",
    "Haule": "HAULE",
    "Haulerwijk": "HAULWK",
    "Hauwert": "HAUWRT",
    "Havelte": "HAVLTE",
    "Havelterberg": "HAVLTB",
    "Hazerswoude-Dorp": "HAZDRP",
    "Hazerswoude-Rijndijk": "HAZRDK",
    "Hedel": "HEDEL",
    "Hedikhuizen": "HEDIKH",
    "Hee": "HEE",
    "Heeg": "HEEG",
    "Heel": "HEEL",
    "Heelsum": "HEELSM",
    "Heelweg": "HEELWG",
    "Heemserveen": "HEEMVN",
    "Heemskerk": "HEEMKK",
    "Heemstede": "HEEMST",
    "Heenvliet": "HEENVL",
    "Heerde": "HEERDE",
    "Heerenveen": "HEERVN",
    "Heerewaarden": "HEERWD",
    "Heerhugowaard": "HEERHW",
    "Heerjansdam": "HEERJD",
    "Heerle": "HEERLE",
    "Heerlen": "HEERLN",
    "Heesbeen": "HEESBN",
    "Heesch": "HEESCH",
    "Heesselt": "HEESST",
    "Heeswijk-Dinther": "HEESDT",
    "Heeten": "HEETEN",
    "Heeze": "HEEZE",
    "Hegebeintum": "HEGEBT",
    "Hegelsom": "HEGELS",
    "Hei- en Boeicop": "HEIBCP",
    "Heibloem": "HEIBLM",
    "Heide": "HEIDE",
    "Heijen": "HEIJEN",
    "Heijenrath": "HEIJRT",
    "Heijningen": "HEIJNG",
    "Heikant": "HEIKNT",
    "Heilig Landstichting": "HEILST",
    "Heiligerlee": "HEILGL",
    "Heiloo": "HEILOO",
    "Heinenoord": "HEINND",
    "Heinkenszand": "HEINKZ",
    "Heino": "HEINO",
    "Hekelingen": "HEKELI",
    "Hekendorp": "HEKEND",
    "Helden": "HELDEN",
    "Helenaveen": "HELNVN",
    "Hellendoorn": "HELLDN",
    "Hellevoetsluis": "HELLVS",
    "Hellouw": "HELLW",
    "Hellum": "HELLUM",
    "Helmond": "HELMND",
    "Helvoirt": "HELVRT",
    "Hem": "HEM",
    "Hemelum": "HEMELM",
    "Hemmen": "HEMMEN",
    "Hempens": "HEMPNS",
    "Hemrik": "HEMRIK",
    "Hendrik-Ido-Ambacht": "HENDIA",
    "Hengelo": "HENGOV",
    "Hengelo (Gld)": "HENGGE",
    "Hengevelde": "HENGEV",
    "Hengstdijk": "HENGDK",
    "Hensbroek": "HENSBK",
    "Herbaijum": "HERBJM",
    "Herkenbosch": "HERKBS",
    "Herkingen": "HERKGN",
    "Hernen": "HERNEN",
    "Herpen": "HERPEN",
    "Herpt": "HERPT",
    "Herten": "HERTEN",
    "Hertme": "HERTME",
    "Herveld": "HERVLD",
    "Herwen": "HERWEN",
    "Herwijnen": "HERWNN",
    "Heteren": "HETERN",
    "Heukelom": "HEUKLO",
    "Heukelum": "HEUKLU",
    "Heumen": "HEUMEN",
    "Heusden Asten": "HEUSDA",
    "Heusden Heusden": "HEUSDH",
    "Heveadorp": "HEVDRP",
    "Heythuysen": "HEYTHS",
    "Hezingen": "HEZING",
    "Hiaure": "HIAURE",
    "Hichtum": "HICHTM",
    "Hidaard": "HIDRD",
    "Hierden": "HIERDN",
    "Hieslum": "HIESLM",
    "Hijken": "HIJKEN",
    "Hijum": "HIJUM",
    "Hilaard": "HILRD",
    "Hillegom": "HILLGM",
    "Hilvarenbeek": "HILVBK",
    "Hilversum": "HILVSM",
    "Hindeloopen": "HINDLP",
    "Hinnaard": "HINNRD",
    "Hippolytushoef": "HIPPHF",
    "Hitzum": "HITZUM",
    "Hobrede": "HOBRDE",
    "Hoedekenskerke": "HOEDKK",
    "Hoef en Haag": "HOEFHG",
    "Hoek": "HOEK",
    "Hoek van Holland": "HOEKVH",
    "Hoenderloo Apeldoorn": "HOENDA",
    "Hoenderloo Ede": "HOENDE",
    "Hoensbroek": "HOENBR",
    "Hoenzadriel": "HOENZD",
    "Hoevelaken": "HOEVLK",
    "Hoeven": "HOEVEN",
    "Hoge Hexel": "HOGEHX",
    "Hollandsche Rading": "HOLLRD",
    "Hollandscheveld": "HOLLVD",
    "Hollum": "HOLLUM",
    "Holsloot": "HOLSLT",
    "Holten": "HOLTEN",
    "Holthees": "HOLTHS",
    "Holtheme": "HOLTHM",
    "Holthone": "HOLTHN",
    "Holtum": "HOLTUM",
    "Holwerd": "HOLWRD",
    "Holwierde": "HOLWDE",
    "Hommerts": "HOMMRT",
    "Homoet": "HOMOET",
    "Honselersdijk": "HONSDK",
    "Hoofddorp": "HOOFDD",
    "Hoofdplaat": "HOOFDP",
    "Hoog Soeren": "HOOGSR",
    "Hoog-Keppel": "HOOGKP",
    "Hoogblokland": "HOOGBL",
    "Hooge Mierde": "HOOGEM",
    "Hooge Zwaluwe": "HOOGZW",
    "Hoogeloon": "HOOGLN",
    "Hoogenweg": "HOOGWG",
    "Hoogerheide": "HOOGHD",
    "Woensdrecht": "WOENSD",
    "Hoogersmilde M-Drenthe": "HOOGSM",
    "Hoogersmilde Westerveld": "HOOGSW",
    "Hoogeveen": "HOOGVN",
    "Hoogezand": "HOOGZD",
    "Hooghalen": "HOOGHL",
    "Hoogkarspel": "HOOGKS",
    "Hoogland": "HOOGLD",
    "Hooglanderveen": "HOOGLV",
    "Hoogmade": "HOOGMD",
    "Hoogvliet Rotterdam": "HOOGVL",
    "Hoogwoud": "HOOGWD",
    "Hoorn Fr": "HOORFR",
    "Hoorn NH": "HOORNH",
    "Hoornaar": "HOORNR",
    "Hoornsterzwaag": "HOORZW",
    "Horn": "HORN",
    "Hornhuizen": "HORNHZ",
    "Horssen": "HORSSN",
    "Horst": "HORST",
    "Houten": "HOUTEN",
    "Houtigehage": "HOUTHG",
    "Houwerzijl": "HOUWZL",
    "Huijbergen": "HUIJBG",
    "Huis ter Heide DR": "HUISDR",
    "Huis ter Heide UT": "HUISUT",
    "Huisduinen": "HUISDN",
    "Huisseling": "HUISSL",
    "Huissen": "HUISSN",
    "Huizen": "HUIZEN",
    "Huizinge": "HUIZNG",
    "Hulsberg": "HULSBG",
    "Hulsel": "HULSEL",
    "Hulshorst": "HULSHT",
    "Hulst": "HULST",
    "Hulten": "HULTEN",
    "Hummelo": "HUMMLO",
    "Huns": "HUNS",
    "Hunsel": "HUNSEL",
    "Hurdegaryp": "HURDGP",
    "Hurwenen": "HURWNN",
    "IJhorst": "IJHRST",
    "IJlst": "IJLST",
    "IJmuiden": "IJMDN",
    "IJsselham": "IJSSHM",
    "IJsselmuiden": "IJSSMD",
    "IJsselstein": "IJSSST",
    "IJzendijke": "IJZNDK",
    "IJzendoorn": "IJZDRN",
    "Idaerd": "IDAERD",
    "Idsegahuizum": "IDSGHZ",
    "Idskenhuizen": "IDSKHZ",
    "Idzega": "IDZEGA",
    "Iens": "IENS",
    "Ilpendam": "ILPNDM",
    "Indijk": "INDIJK",
    "Ingber": "INGBER",
    "Ingelum": "INGELM",
    "Ingen": "INGEN",
    "It Heidenskip": "ITHEIK",
    "Itens": "ITENS",
    "Ittervoort": "ITTERV",
    "Jaarsveld": "JAARSV",
    "Jabeek": "JABEEK",
    "Jannum": "JANNUM",
    "Jellum": "JELLUM",
    "Jelsum": "JELSUM",
    "Jirnsum": "JIRNSM",
    "Jislum": "JISLUM",
    "Jisp": "JISP",
    "Jistrum": "JISTRM",
    "Jonkerslan": "JONKLN",
    "Jonkersvaart": "JONKVT",
    "Joppe": "JOPPE",
    "Jorwert": "JORWRT",
    "Joure": "JOURE",
    "Jouswier": "JOUSWR",
    "Jubbega": "JUBBGA",
    "Julianadorp": "JULIDP",
    "Jutrijp": "JUTRP",
    "Kaag": "KAAG",
    "Kaard": "KAARD",
    "Kaatsheuvel": "KAATSH",
    "Kalenberg": "KALENB",
    "Kallenkote": "KALLKT",
    "Kamerik": "KAMERK",
    "Kampen": "KAMPEN",
    "Kamperland": "KAMPLD",
    "Kamperveen": "KAMPVN",
    "Kantens": "KANTNS",
    "Kapel Avezaath Tiel": "KAPATI",
    "Kapel-Avezaath Buren": "KAPABU",
    "Kapelle": "KAPLLE",
    "Kapellebrug": "KAPLBG",
    "Katlijk": "KATLK",
    "Kats": "KATS",
    "Kattendijke": "KATTDK",
    "Katwijk NB": "KATWNB",
    "Katwijk ZH": "KATWZH",
    "Katwoude": "KATWDE",
    "Kedichem": "KEDCHM",
    "Keent": "KEENT",
    "Keijenborg": "KEIJNB",
    "Kekerdom": "KEKERD",
    "Kelpen-Oler": "KELPOL",
    "Kerk Avezaath Tiel": "KERKTI",
    "Kerk-Avezaath Buren": "KERKBU",
    "Kerkdriel": "KERKDR",
    "Kerkenveld": "KERKVD",
    "Kerkrade": "KERKRD",
    "Kerkwerve": "KERKWV",
    "Kerkwijk": "KERKWK",
    "Kessel": "KESSEL",
    "Kesteren": "KESTRN",
    "Kiel-Windeweer": "KIELWW",
    "Kilder": "KILDER",
    "Kimswerd": "KIMSWD",
    "Kinderdijk": "KINDDK",
    "Kinnum": "KINNUM",
    "Klaaswaal": "KLAASW",
    "Klarenbeek Apeldoorn": "KLARAD",
    "Klarenbeek Voorst": "KLARVO",
    "Klazienaveen": "KLAZVN",
    "Klazienaveen-Noord": "KLAZND",
    "Klein Zundert": "KLEINZ",
    "Klijndijk": "KLIJND",
    "Klimmen": "KLIMMN",
    "Kloetinge": "KLOETG",
    "Kloetinge Kapelle": "KLOETK",
    "Klooster Lidlum": "KLOLID",
    "Kloosterburen": "KLOOSB",
    "Kloosterhaar": "KLOOSH",
    "Kloosterhaar Twenterand": "KLOOST",
    "Kloosterzande": "KLOOSZ",
    "Klundert": "KLUNDT",
    "Knegsel": "KNEGSL",
    "Koarnjum": "KOARNJ",
    "Kockengen": "KOCKGN",
    "Koedijk": "KOEDLD",
    "Koedijk Alkmaar": "KOEDAL",
    "Koekange": "KOEKNG",
    "Koewacht": "KOEWT",
    "Kolderwolde": "KOLDWD",
    "Kolham": "KOLHAM",
    "Kolhorn": "KOLHRN",
    "Kollum": "KOLLUM",
    "Kollumerpomp": "KOLLPP",
    "Kollumerzwaag": "KOLLZW",
    "Kommerzijl": "KOMMZL",
    "Koningsbosch": "KONGBS",
    "Koningslust": "KONLST",
    "Koog aan de Zaan": "KOOGZN",
    "Koolwijk": "KOOLWK",
    "Kootstertille": "KOOTTL",
    "Kootwijk": "KOOTWK",
    "Kootwijkerbroek": "KOOTWB",
    "Kornhorn": "KORNHN",
    "Kornwerderzand": "KORNWZ",
    "Kortehemmen": "KORTHM",
    "Kortenhoef": "KORTHF",
    "Kortgene": "KORTGN",
    "Koudekerk aan den Rijn": "KOUDRN",
    "Koudekerke": "KOUDKK",
    "Koudum": "KOUDUM",
    "Koufurderrige": "KOUFDR",
    "Krabbendijke": "KRABDK",
    "Kraggenburg": "KRAGBG",
    "Kreileroord": "KREILD",
    "Krewerd": "KREWRD",
    "Krimpen aan de Lek": "KRIMLK",
    "Krimpen aan den IJssel": "KRIMIJ",
    "Kring van Dorth": "KRINGD",
    "Krommenie": "KROMMN",
    "Kronenberg": "KRONBG",
    "Kropswolde": "KROPSW",
    "Kruiningen": "KRUING",
    "Kruisland": "KRUISL",
    "Kubaard": "KUBRD",
    "Kudelstaart": "KUDLST",
    "Kuinre": "KUINRE",
    "Kuitaart": "KUITRT",
    "Kwadendamme": "KWADDM",
    "Kwadijk": "KWADK",
    "Kwintsheul": "KWINTH",
    "Laag Zuthem": "LAAGZU",
    "Laag-Keppel": "LAAGKP",
    "Laag-Soeren": "LAAGSR",
    "Lage Mierde": "LAGEMD",
    "Lage Vuursche": "LAGEVS",
    "Lage Zwaluwe": "LAGEZW",
    "Lageland": "LAGELD",
    "Lageland GN": "LAGEGN",
    "Lageland Gem Slochteren": "LAGELS",
    "Lambertschaag": "LAMBHG",
    "Lamswaarde": "LAMSWD",
    "Landerum": "LANDRM",
    "Landgraaf": "LANDGF",
    "Landhorst": "LANDHT",
    "Landsmeer": "LANDMR",
    "Langbroek": "LANGBK",
    "Langedijke": "LANGDK",
    "Langelille": "LANGLL",
    "Langelo": "LANGLO",
    "Langenboom": "LANGBM",
    "Langerak": "LANGRK",
    "Langeveen": "LANGVN",
    "Langeweg": "LANGWG",
    "Langezwaag": "LANGZW",
    "Langweer": "LANGWR",
    "Laren GE": "LARNGE",
    "Laren NH": "LARNNH",
    "Laren Nh": "LARNNH",
    "Lathum": "LATHUM",
    "Lattrop-Breklenkamp": "LATTBK",
    "Lauwersoog": "LAUWRG",
    "Lauwerzijl": "LAUWZL",
    "Ledeacker": "LEDEAK",
    "Leek": "LEEK",
    "Leende": "LEENDE",
    "Leens": "LEENS",
    "Leerbroek": "LEERBK",
    "Leerdam": "LEERDM",
    "Leermens": "LEERMS",
    "Leersum": "LEERSM",
    "Leeuwarden": "LEEUWD",
    "Legemeer": "LEGEMR",
    "Leiden": "LEIDEN",
    "Leiderdorp": "LEIDDP",
    "Leidschendam": "LEIDDM",
    "Leimuiden": "LEIMDN",
    "Leimuiderbrug": "LEIMBG",
    "Lekkerkerk": "LEKKKK",
    "Lekkum": "LEKKUM",
    "Lellens": "LELLNS",
    "Lelystad": "LELYSD",
    "Lemele": "LEMELE",
    "Lemelerveld": "LEMEVD",
    "Lemiers": "LEMRS",
    "Lemmer": "LEMMER",
    "Lengel": "LENGEL",
    "Lent": "LENT",
    "Leons": "LEONS",
    "Lepelstraat": "LEPELS",
    "Lettelbert": "LETTBT",
    "Lettele": "LETTLE",
    "Leunen": "LEUNEN",
    "Leur": "LEUR",
    "Leusden": "LEUSDN",
    "Leuth": "LEUTH",
    "Leutingewolde": "LEUTWD",
    "Leuvenheim": "LEUVHM",
    "Leveroy": "LEVROY",
    "Lewedorp": "LEWEDP",
    "Lexmond": "LEXMND",
    "Lichtaard": "LICHTD",
    "Lichtenvoorde": "LICHVD",
    "Liempde": "LIEMPD",
    "Lienden": "LIENDN",
    "Lierderholthuis": "LIERHH",
    "Lieren": "LIEREN",
    "Lierop": "LIEROP",
    "Lies": "LIES",
    "Lieshout": "LIESHT",
    "Liessel": "LIESSL",
    "Lievelde": "LIEVLD",
    "Lieveren": "LIEVRN",
    "Lijnden": "LIJNDN",
    "Limbricht": "LIMBRT",
    "Limmen": "LIMMEN",
    "Linde": "LINDE",
    "Linden": "LINDEN",
    "Linne": "LINNE",
    "Linschoten": "LINSCH",
    "Lioessens": "LIOESS",
    "Lippenhuizen": "LIPPHZ",
    "Lisse": "LISSE",
    "Lisserbroek": "LISSBR",
    "Lith": "LITH",
    "Lithoijen": "LITHN",
    "Lobith": "LOBITH",
    "Lochem": "LOCHEM",
    "Loenen": "LOENEN",
    "Loenen aan de Vecht": "LOENVT",
    "Loenersloot": "LOENSL",
    "Loenga": "LOENGA",
    "Loerbeek": "LOERBK",
    "Lollum": "LOLLUM",
    "Lomm": "LOMM",
    "Longerhouw": "LONGHW",
    "Loo Gld Duiven": "LOODV",
    "Loo Gld Lingewaard": "LOOLW",
    "Loon": "LOON",
    "Loon op Zand": "LOONZD",
    "Loosbroek": "LOOSBK",
    "Loosdrecht": "LOOSDR",
    "Loozen": "LOOZEN",
    "Lopik": "LOPIK",
    "Lopikerkapel": "LOPKKP",
    "Loppersum": "LOPPSM",
    "Losdorp": "LOSDRP",
    "Losser": "LOSSER",
    "Lottum": "LOTTUM",
    "Lucaswolde": "LUCASW",
    "Luddeweer": "LUDDWR",
    "Luinjeberd": "LUINBD",
    "Lunteren": "LUNTRN",
    "Lutjebroek": "LUTJBK",
    "Lutjegast": "LUTJGT",
    "Lutjewinkel": "LUTJWK",
    "Luttelgeest": "LUTTGT",
    "Lutten": "LUTTEN",
    "Luttenberg": "LUTTBG",
    "Luxwoude": "LUXWDE",
    "Luyksgestel": "LUYKGS",
    "Lytsewierrum": "LYTSWM",
    "Maarheeze": "MAARHZ",
    "Maarn": "MAARN",
    "Maarsbergen": "MAARSB",
    "Maarssen": "MAARSS",
    "Maartensdijk": "MAARTD",
    "Maasbommel": "MAASBL",
    "Maasbracht": "MAASBT",
    "Maasbree": "MAASBR",
    "Maasdam": "MAASDM",
    "Maasdijk": "MAASDK",
    "Maashees": "MAASHS",
    "Maasland": "MAASLD",
    "Maassluis": "MAASSL",
    "Maastricht": "MAASTR",
    "Maastricht-Airport": "MAASAP",
    "Maasvlakte Rotterdam": "MAASVL",
    "Macharen": "MACHRN",
    "Made": "MADE",
    "Makkinga": "MAKKNG",
    "Makkum": "MAKKUM",
    "Malden": "MALDEN",
    "Mander": "MANDER",
    "Manderveen": "MANDVN",
    "Mantgum": "MANTGM",
    "Mantinge": "MANTNG",
    "Maren-Kessel": "MARKES",
    "Margraten": "MARGRT",
    "Maria Hoop": "MARIHP",
    "Mariahout": "MARIHT",
    "Mariaparochie": "MARIPR",
    "Marienberg": "MARIBG",
    "Marienheem": "MARIHM",
    "Marienvelde": "MARIVD",
    "Marijenkampen": "MARKMP",
    "Markelo": "MARKLO",
    "Marken": "MARKEN",
    "Markenbinnen": "MARKBI",
    "Marknesse": "MARKNS",
    "Marle": "MARLE",
    "Marrum": "MARRUM",
    "Marsum": "MARSUM",
    "Marum": "MARUM",
    "Marwijksoord": "MARWKD",
    "Mastenbroek Kampen": "MASTKP",
    "Mastenbroek Zwartewlnd": "MASTZW",
    "Matsloot": "MATSLT",
    "Maurik": "MAURIK",
    "Mechelen": "MECHLN",
    "Medemblik": "MEDMBL",
    "Meeden": "MEEDEN",
    "Meedhuizen": "MEEDHZ",
    "Meerkerk": "MEERKK",
    "Meerlo": "MEERLO",
    "Meerssen": "MEERSS",
    "Meerstad": "MEERSD",
    "Meeuwen": "MEEUWN",
    "Megchelen": "MEGHLN",
    "Megen": "MEGEN",
    "Meijel": "MEIJEL",
    "Melderslo": "MELDSL",
    "Melick": "MELICK",
    "Meliskerke": "MELISK",
    "Melissant": "MELISS",
    "Menaam": "MENAAM",
    "Mensingeweer": "MENSWR",
    "Meppel": "MEPPEL",
    "Meppen": "MEPPEN",
    "Merkelbeek": "MERKBK",
    "Merselo": "MERSLO",
    "Meteren": "METERN",
    "Meterik": "METERK",
    "Metslawier": "METSWR",
    "Mheer": "MHEER",
    "Middelaar": "MIDDLR",
    "Middelburg": "MIDDBG",
    "Middelharnis": "MIDDHS",
    "Middelie": "MIDDLI",
    "Middelstum": "MIDDLS",
    "Middenbeemster": "MIDDBR",
    "Middenmeer": "MIDDMR",
    "Midlaren": "MIDLRN",
    "Midlum": "MIDLUM",
    "Midsland": "MIDSLD",
    "Midwolda": "MIDWDA",
    "Midwolde": "MIDWDE",
    "Midwoud": "MIDWD",
    "Miedum": "MIEDUM",
    "Mierlo": "MIERLO",
    "Mijdrecht": "MIJDRT",
    "Mijnsheerenland": "MIJNSH",
    "Mildam": "MILDAM",
    "Milheeze": "MILHZE",
    "Mill": "MILL",
    "Millingen aan de Rijn": "MILLRN",
    "Milsbeek": "MILSBK",
    "Minnertsga": "MINNSG",
    "Mirns": "MIRNS",
    "Moddergat": "MODDGT",
    "Moerdijk": "MOERDK",
    "Moergestel": "MOERGL",
    "Moerkapelle": "MOERKP",
    "Moerstraten": "MOERST",
    "Molenaarsgraaf": "MOLGRF",
    "Molenhoek": "MOLNHK",
    "Molenschot": "MOLNST",
    "Molkwerum": "MOLKWR",
    "Monnickendam": "MONNKD",
    "Monster": "MONSTR",
    "Montfoort": "MONTUT",
    "Montfort": "MONTLI",
    "Mook": "MOOK",
    "Mookhoek": "MOOKHK",
    "Moordrecht": "MOORDR",
    "Moorveld": "MOORVD",
    "Morra": "MORRA",
    "Muiden": "MUIDEN",
    "Muiderberg": "MUIDBG",
    "Munein": "MUNEIN",
    "Munnekeburen": "MUNNBN",
    "Munnekezijl": "MUNNZL",
    "Munstergeleen": "MUNSTG",
    "Muntendam": "MUNTDM",
    "Mussel": "MUSSEL",
    "Musselkanaal": "MUSSKL",
    "Naaldwijk": "NAALDW",
    "Naarden": "NAARDN",
    "Nagele": "NAGELE",
    "Nederasselt": "NEDASS",
    "Nederhemert": "NEDHEM",
    "Nederhorst den Berg": "NEDHBG",
    "Nederland": "NEDLND",
    "Nederweert": "NEDWRT",
    "Nederweert-Eind": "NEDEIN",
    "Neede": "NEEDE",
    "Neer": "NEER",
    "Neerijnen": "NEERNN",
    "Neeritter": "NEERTT",
    "Neerkant": "NEERKT",
    "Neerlangel": "NEERLG",
    "Neerloon": "NEERLN",
    "Nes": "NESBO",
    "Nes Ameland": "NESAM",
    "Nes Dongeradeel": "NESDO",
    "Netersel": "NETERS",
    "Netterden": "NETTDN",
    "Niawier": "NIAWR",
    "Nibbixwoud": "NIBBWD",
    "Niebert": "NIEBRT",
    "Niehove": "NIEHVE",
    "Niekerk De Marne": "NIEKDM",
    "Niekerk Grootegast": "NIEKGG",
    "Nietap": "NIETAP",
    "Nieuw Annerveen": "NWANNV",
    "Nieuw Beerta": "NWBEER",
    "Nieuw Buinen": "NWBUIN",
    "Nieuw Heeten": "NWHEET",
    "Nieuw Namen": "NWNAMN",
    "Nieuw Scheemda": "NWSCHD",
    "Nieuw- en Sint Joosland": "NWSTJL",
    "Nieuw-Amsterdam": "NWAMST",
    "Nieuw-Balinge": "NWBALG",
    "Nieuw-Beijerland": "NWBEIJ",
    "Nieuw-Buinen": "NWBUIN",
    "Nieuw-Dordrecht": "NWDORD",
    "Nieuw-Lekkerland": "NWLEKK",
    "Nieuw-Roden": "NWRODN",
    "Nieuw-Schoonebeek": "NWSCHB",
    "Nieuw-Vennep": "NWVNNP",
    "Nieuw-Vossemeer": "NWVOSS",
    "Nieuw-Weerdinge": "NWWEER",
    "Nieuwaal": "NWAAL",
    "Nieuwdorp": "NWDORP",
    "Nieuwe Niedorp": "NWNIED",
    "Nieuwe Pekela": "NWPEKL",
    "Nieuwe Wetering": "NWWETR",
    "Nieuwe-Tonge": "NWTONG",
    "Nieuwebrug": "NWBRUG",
    "Nieuwediep": "NWDIEP",
    "Nieuwegein": "NWGEIN",
    "Nieuwehorne": "NWHORN",
    "Nieuwendijk": "NWDIJK",
    "Nieuwer Ter Aa": "NWTRAA",
    "Nieuwerbrug aan den Rijn": "NWBRRN",
    "Nieuwerkerk": "NWKERK",
    "Nieuwerkerk ad IJssel": "NWKKIJ",
    "Nieuweroord": "NWOORH",
    "Nieuweroord M-Drenthe": "NWOORM",
    "Nieuwersluis": "NWSLUI",
    "Nieuweschoot": "NWSCHT",
    "Nieuwkoop": "NWKOOP",
    "Nieuwkuijk": "NWKUIJ",
    "Nieuwland": "NWLAND",
    "Nieuwlande": "NWLNDH",
    "Nieuwlande Coevorden": "NWLNDC",
    "Nieuwleusen": "NWLEUS",
    "Nieuwolda": "NWOLDA",
    "Nieuwpoort": "NWPOOR",
    "Nieuwstadt": "NWSTAD",
    "Nieuwveen": "NWVEEN",
    "Nieuwvliet": "NWVLIE",
    "Niezijl": "NIEZL",
    "Niftrik": "NIFTRK",
    "Nigtevecht": "NIGTEV",
    "Nij Altoenae": "NIJALT",
    "Nij Beets": "NIJBTS",
    "Nijbroek": "NIJBRK",
    "Nijeberkoop": "NIJBKP",
    "Nijega": "NIJEGA",
    "Nijehaske": "NIJEHK",
    "Nijeholtpade": "NIJEHP",
    "Nijeholtwolde": "NIJEHW",
    "Nijelamer": "NIJELM",
    "Nijemirdum": "NIJEMD",
    "Nijensleek": "NIJESK",
    "Nijetrijne": "NIJETN",
    "Nijeveen": "NIJEVN",
    "Nijhuizum": "NIJHZM",
    "Nijkerk": "NIJKRK",
    "Nijkerkerveen": "NIJKVN",
    "Nijland": "NIJLND",
    "Nijlande": "NIJLDE",
    "Nijmegen": "NIJMGN",
    "Nijverdal": "NIJVDL",
    "Nispen": "NISPEN",
    "Nisse": "NISSE",
    "Nistelrode": "NISTRD",
    "Noardburgum": "NOARDB",
    "Nooitgedacht": "NOOITG",
    "Noorbeek": "NOORBK",
    "Noord-Scharwoude": "NDSCHA",
    "Noord-Sleen": "NDSLEE",
    "Noordbeemster": "NDBEEM",
    "Noordbroek": "NDBROE",
    "Noordeinde Gld": "NDEIGE",
    "Noordeinde NH": "NDEINH",
    "Noordeloos": "NDLOOS",
    "Noorden": "NDEN",
    "Noordgouwe": "NDGOUW",
    "Noordhoek": "NDHOEK",
    "Noordhorn": "NDHORN",
    "Noordlaren": "NDLARN",
    "Noordscheschut": "NDSCHU",
    "Noordwelle": "NDWELL",
    "Noordwijk GR": "NDWKGR",
    "Noordwijk ZH": "NDWKZH",
    "Noordwijkerhout": "NDWKHT",
    "Noordwolde Fr": "NDWLFR",
    "Noordwolde GR": "NDWLGR",
    "Nootdorp": "NOOTDP",
    "Norg": "NORG",
    "Notter": "NOTTER",
    "Nuenen": "NUENEN",
    "Nuis": "NUIS",
    "Nuland": "NULAND",
    "Numansdorp": "NUMAND",
    "Nunhem": "NUNHEM",
    "Nunspeet": "NUNSPT",
    "Nuth": "NUTH",
    "Nutter": "NUTTER",
    "OUDWET": "OUDTNG",
    "Obbicht": "OBBCHT",
    "Obdam": "OBDAM",
    "Ochten": "OCHTEN",
    "Odijk": "ODIJK",
    "Odiliapeel": "ODILPL",
    "Odoorn": "ODOORN",
    "Odoornerveen": "ODOORV",
    "Oeffelt": "OEFFLT",
    "Oegstgeest": "OEGSTG",
    "Oene": "OENE",
    "Oentsjerk": "OENTSJ",
    "Offingawier": "OFFGWR",
    "Ohe en Laak": "OHELK",
    "Oijen": "OIJEN",
    "Oirlo": "OIRLO",
    "Oirsbeek": "OIRSBK",
    "Oirschot": "OIRSCT",
    "Oisterwijk": "OISTWK",
    "Okkenbroek": "OKKENB",
    "Olburgen": "OLBRGN",
    "Oldeberkoop": "OLDEBP",
    "Oldebroek": "OLDEBK",
    "Oldeholtpade": "OLDEHP",
    "Oldeholtwolde": "OLDEHW",
    "Oldehove": "OLDEHV",
    "Oldekerk": "OLDEKK",
    "Oldelamer": "OLDELM",
    "Oldemarkt": "OLDEMT",
    "Oldenzaal": "OLZAAL",
    "Oldenzijl": "OLZIJL",
    "Oldeouwer": "OLDEOW",
    "Oldetrijne": "OLDETN",
    "Olst": "OLST",
    "Olterterp": "OLTRTP",
    "Ommel": "OMMEL",
    "Ommen": "OMMEN",
    "Ommeren": "OMMERN",
    "Onderdendam": "ONDERD",
    "Onna": "ONNA",
    "Onnen": "ONNEN",
    "Onstwedde": "ONSTWD",
    "Ooij": "OOIJ",
    "Ooltgensplaat": "OOLTPL",
    "Oost West en Middelbeers": "OWMIDD",
    "Oost-Graftdijk": "OTGRAF",
    "Oost-Souburg": "OTSOUB",
    "Oostburg": "OTBURG",
    "Oostdijk": "OTDIJK",
    "Oosteind": "OTEIND",
    "Oosterbeek": "OTBEEK",
    "Oosterbierum": "OTBIER",
    "Oosterblokker": "OTBLOK",
    "Oosterend FR": "OTENFR",
    "Oosterend NH": "OTENNH",
    "Oosterhesselen": "OTHESS",
    "Oosterhout GE": "OTHTGE",
    "Oosterhout NB": "OTHTNB",
    "Oosterland": "OTLAND",
    "Oosterleek": "OTLEEK",
    "Oosternieland": "OTNIEL",
    "Oosternijkerk": "OTNIJK",
    "Oosterstreek": "OTSTRK",
    "Oosterwijk": "OTWIJK",
    "Oosterwijtwerd": "OTWIJT",
    "Oosterwolde FR": "OTWLFR",
    "Oosterwolde Gld": "OTWLGE",
    "Oosterzee": "OTRZEE",
    "Oosthem": "OOSTHM",
    "Oosthuizen": "OTHUIZ",
    "Oostkapelle": "OTKAPP",
    "Oostknollendam": "OTKNOL",
    "Oostrum FR": "OTRMFR",
    "Oostrum LI": "OTRMLI",
    "Oostvoorne": "OTVOOR",
    "Oostwold Leek": "OTWOLK",
    "Oostwold Oldambt": "OTWOOA",
    "Oostwoud": "OTWOUD",
    "Oostzaan": "OTZAAN",
    "Ootmarsum": "OOTMSM",
    "Opeinde": "OPEIND",
    "Opende": "OPENDE",
    "Ophemert": "OPHMRT",
    "Opheusden": "OPHSDN",
    "Opijnen": "OPIJNN",
    "Oploo": "OPLOO",
    "Opmeer": "OPMEER",
    "Oppenhuizen": "OPPNHZ",
    "Opperdoes": "OPPRDS",
    "Oranje": "ORANJE",
    "Oranjewoud": "ORANWD",
    "Orvelte": "ORVLTE",
    "Ospel": "OSPEL",
    "Oss": "OSS",
    "Ossendrecht": "OSSDRT",
    "Ossenisse": "OSSNIS",
    "Ossenwaard": "OSSNWD",
    "Ossenzijl": "OSSNZL",
    "Oterleek": "OTERLK",
    "Otterlo": "OTTRLO",
    "Ottersum": "OTTRSM",
    "Ottoland": "OTTOLD",
    "Oud Ade": "OUDADE",
    "Oud Annerveen": "OUDANN",
    "Oud Gastel": "OUDGAS",
    "Oud Ootmarsum": "OUDOOT",
    "Oud Zuilen": "OUDZLN",
    "Oud-Alblas": "OUDALB",
    "Oud-Beijerland": "OUDBLD",
    "Oud-Vossemeer": "OUDVOS",
    "Ouddorp ZH": "OUDDRP",
    "Oude Meer": "OUDEMR",
    "Oude Niedorp": "OUDNDP",
    "Oude Pekela": "OUDPEK",
    "Oude Wetering": "OUDWET",
    "Oude Willem": "OUDWIL",
    "Oudebildtzijl": "OUDBZL",
    "Oudega De Fryske Marren": "OUDGFM",
    "Oudega Smallingerland": "OUDGSL",
    "Oudega Sudwest-Fryslan": "OUDGSF",
    "Oudehaske": "OUDHSK",
    "Oudehorne": "OUDHRN",
    "Oudelande": "OUDLND",
    "Oudemirdum": "OUDMDM",
    "Oudemolen DR": "OUDMDR",
    "Oudemolen NB": "OUDMNB",
    "Oudenbosch": "OUDBOS",
    "Oudendijk": "OUDNDK",
    "Oudenhoorn": "OUDNHN",
    "Ouderkerk aan de Amstel": "ODKAMS",
    "Ouderkerk aan den IJssel": "ODKIJS",
    "Oudeschans": "OUDSCS",
    "Oudeschild": "OUDSCD",
    "Oudeschip": "OUDSCP",
    "Oudeschoot": "OUDSCT",
    "Oudesluis": "OUDSLS",
    "Oudewater": "OUDWTR",
    "Oudezijl": "OUDEZL",
    "Oudheusden": "OUDHSD",
    "Oudkarspel": "OUDKLD",
    "Oudkarspel Schagen": "OUDKSG",
    "Oudorp": "OUDORP",
    "Oudwoude": "OUDWDE",
    "Ouwerkerk": "OUWKRK",
    "Ouwster-Nijega": "OUWNIJ",
    "Ouwsterhaule": "OUWHLE",
    "Overasselt": "OVERAS",
    "Overberg": "OVERBG",
    "Overdinkel": "OVERDK",
    "Overlangel": "OVERLA",
    "Overloon": "OVERLN",
    "Overschild": "OVERSD",
    "Overslag": "OVERSL",
    "Overveen": "OVERVN",
    "Ovezande": "OVEZAN",
    "Paasloo": "PAASLO",
    "Paesens": "PAESNS",
    "Pannerden": "PANNDN",
    "Panningen": "PANNGN",
    "Papekop": "PAPEKP",
    "Papendrecht": "PAPDRT",
    "Papenhoven": "PAPHVN",
    "Papenvoort": "PAPVRT",
    "Parrega": "PARRGA",
    "Paterswolde": "PATWLD",
    "Peest": "PEEST",
    "Peins": "PEINS",
    "Peize": "PEIZE",
    "Peperga": "PEPRGA",
    "Pernis Rotterdam": "PERNIS",
    "Persingen": "PERSGN",
    "Pesse Hoogeveen": "PESSEH",
    "Pesse Westerveld": "PESSEW",
    "Petten": "PETTEN",
    "Philippine": "PHILPP",
    "Piaam": "PIAAM",
    "Piershil": "PIERSH",
    "Pieterburen": "PIETBN",
    "Pietersbierum": "PIETBM",
    "Pieterzijl": "PIETZL",
    "Pijnacker": "PIJNAK",
    "Pingjum": "PINGJM",
    "Plasmolen": "PLASML",
    "Poederoijen": "POEDRN",
    "Poeldijk": "POELDK",
    "Polsbroek": "POLSBK",
    "Poortugaal": "POORTG",
    "Poortvliet": "POORTV",
    "Poppenwier": "POPPWR",
    "Posterholt": "POSTHT",
    "Prinsenbeek": "PRINSB",
    "Puiflijk": "PUIFLK",
    "Punthorst": "PUNTHT",
    "Purmer Edam-Volendam": "PURMEV",
    "Purmer Waterland": "PURMWA",
    "Purmerend": "PURMED",
    "Purmerland": "PURMLD",
    "Puth": "PUTH",
    "Putte": "PUTTE",
    "Putten": "PUTTEN",
    "Puttershoek": "PUTTHK",
    "Raalte": "RAALTE",
    "Raamsdonk": "RAAMDK",
    "Raamsdonksveer": "RAAMDV",
    "Raard": "RAARD",
    "Radewijk": "RADEWK",
    "Radio Kootwijk": "RADIOK",
    "Raerd": "RAERD",
    "Randwijk": "RANDWK",
    "Ransdaal": "RANSDL",
    "Rasquert": "RASQRT",
    "Ravenstein": "RAVSTN",
    "Ravenswaaij": "RAVWIJ",
    "Ravenswoud": "RAVNWD",
    "Readtsjerk": "READTK",
    "Reahus": "REAHUS",
    "Reduzum": "REDZUM",
    "Reek": "REEK",
    "Reeuwijk": "REEUWK",
    "Reijmerstok": "REIJMS",
    "Reitsum": "REITSM",
    "Rekken": "REKKEN",
    "Renesse": "RENESS",
    "Renkum": "RENKUM",
    "Renswoude": "RENSWD",
    "Ressen": "RESSEN",
    "Retranchement": "RETRMT",
    "Reusel": "REUSEL",
    "Reutum": "REUTUM",
    "Reuver": "REUVER",
    "Rha": "RHA",
    "Rheden": "RHEDEN",
    "Rhee": "RHEE",
    "Rheeze": "RHEEZE",
    "Rheezerveen": "RHEEVN",
    "Rhenen": "RHENEN",
    "Rhenoy": "RHENOY",
    "Rhoon": "RHOON",
    "Ridderkerk": "RIDDKK",
    "Ried": "RIED",
    "Riel": "RIEL",
    "Rien": "RIEN",
    "Riethoven": "RIETHV",
    "Rietmolen": "RIETML",
    "Rijen": "RIJEN",
    "Rijkevoort": "RIJKVT",
    "Rijkevoort-De Walsert": "RIJKWL",
    "Rijnsaterwoude": "RIJNWD",
    "Rijnsburg": "RIJNBG",
    "Rijpwetering": "RIJPWT",
    "Rijs": "RIJS",
    "Rijsbergen": "RIJSBG",
    "Rijsenhout": "RIJSHT",
    "Rijssen": "RIJSSN",
    "Rijswijk (GLD)": "RIJSGE",
    "Rijswijk (NB)": "RIJSNB",
    "Rijswijk ZH": "RIJSZH",
    "Rilland": "RILLND",
    "Rinsumageast": "RINSMG",
    "Ritthem": "RITTHM",
    "Rockanje": "ROCKNJ",
    "Roden": "RODEN",
    "Roderesch": "RODRSC",
    "Roderwolde": "RODRWD",
    "Roelofarendsveen": "ROELVN",
    "Roermond": "ROERMD",
    "Rogat": "ROGAT",
    "Roggel": "ROGGEL",
    "Rohel": "ROHEL",
    "Rolde": "ROLDE",
    "Roodeschool": "ROODSC",
    "Roosendaal": "ROOSDL",
    "Roosteren": "ROOSTR",
    "Rosmalen": "ROSMLN",
    "Rossum GE": "ROSSGE",
    "Rossum OV": "ROSSOV",
    "Roswinkel": "ROSWKL",
    "Rotstergaast": "ROTSGT",
    "Rotsterhaule": "ROTSHL",
    "Rotterdam": "ROTTDM",
    "Rotterdam-Albrandswaard": "ROTALB",
    "Rottevalle": "ROTTVL",
    "Rottum Fr": "ROTTFR",
    "Rottum GR": "ROTTGR",
    "Rouveen": "ROUVN",
    "Rozenburg NH": "ROZNNH",
    "Rozenburg ZH": "ROZNZH",
    "Rozendaal": "ROZNDL",
    "Rucphen": "RUCPHN",
    "Ruigahuizen": "RUIGHZ",
    "Ruinen De Wolden": "RUINDW",
    "Ruinen Westerveld": "RUINWV",
    "Ruinerwold": "RUINWD",
    "Rumpt": "RUMPT",
    "Rutten": "RUTTEN",
    "Ruurlo": "RUURLO",
    "Ryptsjerk": "RYPTSK",
    "Saaksum": "SAAKSM",
    "Saasveld": "SAASVD",
    "Saaxumhuizen": "SAAXHZ",
    "Sambeek": "SAMBK",
    "Sandfirden": "SANDFD",
    "Santpoort-Noord": "SANTPN",
    "Santpoort-Zuid": "SANTPZ",
    "Sappemeer": "SAPPMR",
    "Sas van Gent": "SASGNT",
    "Sassenheim": "SASSHM",
    "Sauwerd": "SAUWRD",
    "Schagen": "SCHAGN",
    "Schagerbrug": "SCHAGB",
    "Schaijk": "SCHAIJ",
    "Schalkhaar": "SCHAHR",
    "Schalkwijk": "SCHAWK",
    "Schalsum": "SCHASM",
    "Schardam": "SCHADM",
    "Scharendijke": "SCHADK",
    "Scharmer": "SCHAMR",
    "Scharnegoutum": "SCHAGT",
    "Scharsterbrug": "SCHABG",
    "Scharwoude": "SCHAWD",
    "Scheemda": "SCHEDA",
    "Scheerwolde": "SCHEWD",
    "Schellinkhout": "SCHEHT",
    "Schelluinen": "SCHELN",
    "Schermerhorn": "SCHEHN",
    "Scherpenisse": "SCHENS",
    "Scherpenzeel FR": "SCHEFR",
    "Scherpenzeel GE": "SCHEGE",
    "Schettens": "SCHETS",
    "Scheulder": "SCHEDR",
    "Schiedam": "SCHIDM",
    "Schiermonnikoog": "SCHIMO",
    "Schijf": "SCHIJF",
    "Schijndel": "SCHIJN",
    "Schildwolde": "SCHIWD",
    "Schimmert": "SCHIMM",
    "Schin op Geul": "SCHING",
    "Schinnen": "SCHINN",
    "Schinveld": "SCHIVD",
    "Schipborg": "SCHIBG",
    "Schiphol": "SCHIHL",
    "Schiphol-Rijk": "SCHIRK",
    "Schipluiden": "SCHILD",
    "Schokland": "SCHOLD",
    "Schoondijke": "SCHODK",
    "Schoonebeek": "SCHOBK",
    "Schoonhoven": "SCHOHV",
    "Schoonloo": "SCHOLO",
    "Schoonoord": "SCHONO",
    "Schoonrewoerd": "SCHOWD",
    "Schoorl": "SCHOOR",
    "Schore": "SCHORE",
    "Schouwerzijl": "SCHOZL",
    "Schraard": "SCHRRD",
    "Schuinesloot": "SCHUST",
    "Sebaldeburen": "SEBDBR",
    "Sellingen": "SELLNG",
    "Serooskerke Schouwen": "SERSSW",
    "Serooskerke Veere": "SERSVE",
    "Sevenum": "SEVNUM",
    "Sexbierum": "SEXBRM",
    "Sibculo": "SIBCLH",
    "Sibculo Twenteraand": "SIBCLT",
    "Sibrandabuorren": "SIBRBR",
    "Sibrandahus": "SIBRHS",
    "Siddeburen": "SIDDB",
    "Siebengewald": "SIEBGW",
    "Siegerswoude": "SIEGWD",
    "Sijbekarspel": "SIJBKP",
    "Silvolde": "SILVLD",
    "Simonshaven": "SIMNHV",
    "Simpelveld": "SIMPVD",
    "Sinderen": "SINDRN",
    "Sint Agatha": "STAGAT",
    "Sint Annen": "STANNN",
    "Sint Anthonis": "STANTH",
    "Sint Geertruid": "STGEER",
    "Sint Hubert": "STHUBT",
    "Sint Jansklooster": "STJANK",
    "Sint Jansteen": "STJANS",
    "Sint Joost": "STJOOS",
    "Sint Kruis": "STKRUI",
    "Sint Maarten": "STMAAR",
    "Sint Maartensbrug": "STMTBR",
    "Sint Maartensvlotbrug": "STMRVB",
    "Sint Nicolaasga": "STNICG",
    "Sint Odilienberg": "STODIL",
    "Sint Pancras": "STPANC",
    "Sint Philipsland": "STPHIL",
    "Sint-Annaland": "STANNA",
    "Sint-Maartensdijk": "STMTDK",
    "Sint-Michielsgestel": "STMICH",
    "Sint-Oedenrode": "STOEDR",
    "Sintjohannesga": "STJOHA",
    "Sirjansland": "SIRJLD",
    "Sittard": "SITTRD",
    "Skingen": "SKINGN",
    "Slagharen": "SLAGHR",
    "Slappeterp": "SLAPTP",
    "Sleen": "SLEEN",
    "Sleeuwijk": "SLEEUW",
    "Slenaken": "SLENKN",
    "Sliedrecht": "SLIEDR",
    "Slijk-Ewijk": "SLIJKE",
    "Slijkenburg": "SLIJKB",
    "Slochteren": "SLOCHT",
    "Slootdorp": "SLOOTD",
    "Sloten": "SLOTEN",
    "Sluis": "SLUIS",
    "Sluiskil": "SLUISK",
    "Smakt": "SMAKT",
    "Smalle Ee": "SMALEE",
    "Smallebrugge": "SMALBG",
    "Smilde": "SMILDE",
    "Snakkerburen": "SNAKKB",
    "Sneek": "SNEEK",
    "Snelrewaard": "SNELRW",
    "Snikzwaag": "SNIKZW",
    "Soerendonk": "SOERND",
    "Soest": "SOEST",
    "Soesterberg": "SOESTB",
    "Someren": "SOMERN",
    "Sommelsdijk": "SOMMDK",
    "Son en Breugel": "SONBRG",
    "Sondel": "SONDEL",
    "Sonnega": "SONNGA",
    "Spaarndam": "SPAAHL",
    "Spaarndam gem. Haarlem": "SPAAHA",
    "Spanbroek": "SPANBK",
    "Spanga": "SPANGA",
    "Spankeren": "SPANKR",
    "Spannum": "SPANNM",
    "Spaubeek": "SPAUBK",
    "Spier": "SPIERM",
    "Spier Westerveld": "SPIERW",
    "Spierdijk": "SPIERD",
    "Spijk GN": "SPIJKG",
    "Spijk Lingewaal": "SPIJKL",
    "Spijk Rijnwaarden": "SPIJKR",
    "Spijkenisse": "SPIJKN",
    "Spijkerboor DR": "SPKBDR",
    "Spijkerboor NH": "SPKBNH",
    "Sprang-Capelle": "SPRANG",
    "Sprundel": "SPRUND",
    "Spui": "SPUI",
    "St. Willebrord": "STWILL",
    "St.-Annaparochie": "STANNP",
    "St.-Jacobiparochie": "STJACP",
    "Stad aan 't Haringvliet": "STADHV",
    "Stadskanaal": "STADKN",
    "Stampersgat": "STAMPG",
    "Standdaarbuiten": "STANDD",
    "Staphorst": "STAPHS",
    "Starnmeer": "STARNM",
    "Startenhuizen": "STARTL",
    "Startenhuizen Eemsmond": "STARTE",
    "Stavenisse": "STAVNS",
    "Stavoren": "STAVRN",
    "Stedum": "STEDUM",
    "Steenbergen DR": "STNBDR",
    "Steenbergen NB": "STNBNB",
    "Steendam": "STNDAM",
    "Steenderen": "STNDRN",
    "Steenenkamer": "STNKMR",
    "Steensel": "STNSEL",
    "Steenwijk": "STNWK",
    "Steenwijkerwold": "STNWKW",
    "Stegeren": "STEGRN",
    "Steggerda": "STEGGD",
    "Stein": "STEIN",
    "Stellendam": "STELLD",
    "Sterksel": "STERKS",
    "Stevensbeek": "STEVBK",
    "Stevensweert": "STEVWT",
    "Steyl": "STEYL",
    "Stieltjeskanaal": "STIELK",
    "Stiens": "STIENS",
    "Stitswerd": "STITSW",
    "Stokkum": "STOKKM",
    "Stolwijk": "STOLWK",
    "Stompetoren": "STOMPT",
    "Stoutenburg": "STOUTB",
    "Stoutenburg Noord": "STTBND",
    "Stramproy": "STRAMP",
    "Streefkerk": "STREEF",
    "Striep": "STRIEP",
    "Strijbeek": "STRIJB",
    "Strijen": "STRIJN",
    "Strijensas": "STRIJS",
    "Stroe": "STROE",
    "Stroobos": "STROOB",
    "Stuifzand": "STUIFH",
    "Stuifzand M-Drenthe": "STUIFM",
    "Sumar": "SUMAR",
    "Surhuisterveen": "SURHVN",
    "Surhuizum": "SURHZM",
    "Susteren": "SUSTRN",
    "Suwald": "SUWALD",
    "Swalmen": "SWALMN",
    "Sweikhuizen": "SWEIKH",
    "Swichum": "SWICHM",
    "Swifterbant": "SWIFTB",
    "Swolgen": "SWOLGN",
    "Taarlo": "TAARLO",
    "Teeffelen": "TEEFFL",
    "Teerns": "TEERNS",
    "Tegelen": "TEGELN",
    "Ten Boer": "TNBOER",
    "Ten Post": "TNPOST",
    "Ter Aar": "TRAAR",
    "Ter Aard": "TRAARD",
    "Ter Apel": "TRAPEL",
    "Ter Apelkanaal": "TRAPKN",
    "Ter Heijde": "TRHEIE",
    "Ter Idzard": "TRIDZD",
    "Terband": "TRBAND",
    "Terborg": "TRBORG",
    "Terheijden": "TRHEIN",
    "Terherne": "TRHERN",
    "Terhole": "TRHOLE",
    "Terkaple": "TRKAPL",
    "Termunten": "TRMUNT",
    "Termunterzijl": "TRMUZL",
    "Ternaard": "TRNAAR",
    "Terneuzen": "TRNEUZ",
    "Teroele": "TROELE",
    "Terschuur": "TRSCHU",
    "Tersoal": "TRSOAL",
    "Terwispel": "TRWISP",
    "Terwolde": "TRWOLD",
    "Teteringen": "TETRGN",
    "Teuge": "TEUGE",
    "Thesinge": "THESNG",
    "Tholen": "THOLEN",
    "Thorn": "THORN",
    "Tiel": "TIEL",
    "Tiendeveen": "TIENDH",
    "Tiendeveen M-Drenthe": "TIENDM",
    "Tienhoven UT": "TIENUT",
    "Tienhoven ZH": "TIENZH",
    "Tienray": "TIENRY",
    "Tijnje": "TIJNJE",
    "Tilburg": "TILBRG",
    "Tilligte": "TILLGT",
    "Tinallinge": "TINLLG",
    "Tinte": "TINTE",
    "Tirns": "TIRNS",
    "Tjalhuizum": "TJALHZ",
    "Tjalleberd": "TJALLB",
    "Tjerkgaast": "TJERKG",
    "Tjerkwerd": "TJERKW",
    "Tjuchem": "TJUCHM",
    "Tolbert": "TOLBRT",
    "Toldijk": "TOLDK",
    "Tolkamer": "TOLKMR",
    "Tollebeek": "TOLLBK",
    "Tonden": "TONDEN",
    "Toornwerd": "TOORNW",
    "Tricht": "TRICHT",
    "Triemen": "TRIEMN",
    "Tripscompagnie": "TRIPSC",
    "Tubbergen": "TUBBRG",
    "Tuil": "TUIL",
    "Tuitjenhorn": "TUITJH",
    "Tuk": "TUK",
    "Tull en 't Waal": "TULLWL",
    "Twello": "TWELLO",
    "Twijzel": "TWIJZL",
    "Twijzelerheide": "TWIJZH",
    "Twisk": "TWISK",
    "Tynaarlo": "TYNRLO",
    "Tytsjerk": "TYTSJK",
    "Tzum": "TZUM",
    "Tzummarum": "TZUMMR",
    "Ubbena": "UBBENA",
    "Ubbergen": "UBBERG",
    "Uddel": "UDDEL",
    "Uden": "UDEN",
    "Udenhout": "UDENHT",
    "Uffelte": "UFFELT",
    "Ugchelen": "UGCHLN",
    "Uitdam": "UITDAM",
    "Uitgeest": "UITGST",
    "Uithoorn": "UITHRN",
    "Uithuizen": "UITHZN",
    "Uithuizermeeden": "UITHMD",
    "Uitwellingerga": "UITWLL",
    "Uitwijk": "UITWK",
    "Ulestraten": "ULESTR",
    "Ulft": "ULFT",
    "Ulicoten": "ULICOT",
    "Ulrum": "ULRUM",
    "Ulvenhout": "ULVNHT",
    "Ulvenhout AC": "ULVHAC",
    "Ureterp": "URETRP",
    "Urk": "URK",
    "Urmond": "URMOND",
    "Ursem": "URSEM",
    "Ursem gem. S": "URSEMS",
    "Usquert": "USQURT",
    "Utrecht": "UTRECH",
    "Vaals": "VAALS",
    "Vaassen": "VAASSN",
    "Valburg": "VALBRG",
    "Valkenburg LI": "VALKLI",
    "Valkenburg ZH": "VALKZH",
    "Valkenswaard": "VALKWD",
    "Valthe": "VALTHE",
    "Valthermond": "VALTMD",
    "Varik": "VARIK",
    "Varsselder": "VARSSD",
    "Varsseveld": "VARSSV",
    "Vasse": "VASSE",
    "Veelerveen": "VEELRV",
    "Veen": "VEEN",
    "Veendam": "VEENDM",
    "Veenendaal": "VEENDL",
    "Veenhuizen": "VEENHZ",
    "Veeningen": "VEENGN",
    "Veenklooster": "VEENKL",
    "Veenoord": "VEENOO",
    "Veere": "VEERE",
    "Veessen": "VEESSN",
    "Vegelinsoord": "VEGELO",
    "Veghel": "VEGHEL",
    "Velddriel": "VELDDR",
    "Velden": "VELDEN",
    "Veldhoven": "VELDHV",
    "Velp GE": "VELPGE",
    "Velp NB": "VELPNB",
    "Velsen-Noord": "VELSNN",
    "Velsen-Zuid": "VELSNZ",
    "Velserbroek": "VELSBR",
    "Ven-Zelderheide": "VENZEL",
    "Venebrugge": "VENEBG",
    "Venhorst": "VENHRS",
    "Venhuizen": "VENHZN",
    "Venlo": "VENLO",
    "Venray": "VENRAY",
    "Vessem": "VESSEM",
    "Vethuizen": "VETHZN",
    "Veulen": "VEULEN",
    "Vianen NB": "VIANNB",
    "Vianen UT": "VIANUT",
    "Vierakker": "VIERKK",
    "Vierhouten": "VIERHT",
    "Vierhuizen": "VIERHZ",
    "Vierlingsbeek": "VIERLB",
    "Vierpolders": "VIERPL",
    "Vijfhuizen": "VIJFHZ",
    "Vijlen": "VIJLEN",
    "Vilsteren": "VILSTR",
    "Vinkega": "VINKGA",
    "Vinkel": "VINKLM",
    "Vinkel Bernheze": "VINKLB",
    "Vinkenbuurt": "VINKBT",
    "Vinkeveen": "VINKVN",
    "Visvliet": "VISVLT",
    "Vlaardingen": "VLAARD",
    "Vlagtwedde": "VLAGTW",
    "Vledder": "VLEDDE",
    "Vledderveen DR": "VLEDDR",
    "Vledderveen GR": "VLEDGR",
    "Vleuten": "VLEUTN",
    "Vlieland": "VLIELD",
    "Vlierden": "VLIERD",
    "Vlijmen": "VLIJMN",
    "Vlissingen": "VLISSG",
    "Vlist": "VLIST",
    "Vlodrop": "VLODRP",
    "Voerendaal": "VOERDL",
    "Vogelenzang": "VOGELZ",
    "Vogelwaarde": "VOGELW",
    "Volendam": "VOLEND",
    "Volkel": "VOLKEL",
    "Vollenhove": "VOLLHV",
    "Vondelingenplaat Rdam": "VONDPL",
    "Voorburg": "VOORB",
    "Voorhout": "VOORHT",
    "Voorschoten": "VOORSC",
    "Voorst Oude IJsselstreek": "VOOROU",
    "Voorst Voorst": "VOORVO",
    "Voorthuizen": "VOORTH",
    "Vorchten": "VORCHT",
    "Vorden": "VORDEN",
    "Vorstenbosch": "VORSTB",
    "Vortum-Mullem": "VORTML",
    "Vragender": "VRAGDR",
    "Vredenheim": "VREDHM",
    "Vredepeel": "VREDPL",
    "Vreeland": "VREELD",
    "Vries": "VRIES",
    "Vriescheloo": "VRIESL",
    "Vriezenveen": "VRIEZV",
    "Vroomshoop": "VROOMH",
    "Vrouwenakker": "VROUAK",
    "Vrouwenparochie": "VROUPR",
    "Vrouwenpolder": "VROUPD",
    "Vught": "VUGHT",
    "Vuren": "VUREN",
    "Waaksens": "WAAKSS",
    "Waal": "WAAL",
    "Waalre": "WAALRE",
    "Waalwijk": "WAALWK",
    "Waarde": "WAARDE",
    "Waardenburg": "WAARBG",
    "Waarder": "WAARDR",
    "Waardhuizen": "WAARHZ",
    "Waarland": "WAARLD",
    "Waaxens": "WAAXNS",
    "Wachtum": "WACHTM",
    "Waddinxveen": "WADDXV",
    "Wadenoijen": "WADENO",
    "Wagenberg": "WAGENB",
    "Wagenborgen": "WAGNBG",
    "Wageningen": "WAGNGN",
    "Walem": "WALEM",
    "Walsoorden": "WALSRD",
    "Walterswald": "WALTWD",
    "Wamel": "WAMEL",
    "Wanneperveen": "WANNPV",
    "Wanroij": "WANROJ",
    "Wanssum": "WANSSM",
    "Wanswert": "WANSWT",
    "Wapenveld": "WAPNVD",
    "Wapse": "WAPSE",
    "Wapserveen": "WAPSVN",
    "Warder": "WARDER",
    "Warffum": "WARFFM",
    "Warfhuizen": "WARFHZ",
    "Warfstermolen": "WARFSM",
    "Warmenhuizen": "WARMNH",
    "Warmond": "WARMND",
    "Warns": "WARNS",
    "Warnsveld": "WANSVD",
    "Warstiens": "WARSTN",
    "Warten": "WARTEN",
    "Waskemeer": "WASKEM",
    "Waspik": "WASPIK",
    "Wassenaar": "WASSNR",
    "Wateren": "WATERN",
    "Watergang": "WATERG",
    "Waterhuizen": "WATERH",
    "Wateringen": "WATERI",
    "Waterlandkerkje": "WATERK",
    "Waverveen": "WAVERV",
    "Wedde": "WEDDE",
    "Weerselo": "WEERSL",
    "Weert": "WEERT",
    "Weesp": "WEESP",
    "Wehe-den Hoorn": "WEHEDH",
    "Wehl": "WEHL",
    "Weidum": "WEIDUM",
    "Weiteveen": "WEITVN",
    "Wekerom": "WEKERM",
    "Well GE": "WELLGE",
    "Well L": "WELLLI",
    "Wellerlooi": "WELLRL",
    "Welsum": "WELSUM",
    "Wemeldinge": "WEMELD",
    "Wenum Wiesel": "WENUMW",
    "Wergea": "WERGEA",
    "Werkendam": "WERKDM",
    "Werkhoven": "WERKHV",
    "Wernhout": "WERNHT",
    "Wervershoof": "WERVHF",
    "Wesepe": "WESEPE",
    "Wessem": "WESSEM",
    "West-Graftdijk": "WGRAFT",
    "West-Terschelling": "WTERSC",
    "Westbeemster": "WBEEMS",
    "Westbroek": "WBROEK",
    "Westdorp": "WDORP",
    "Westdorpe": "WDORPE",
    "Westendorp": "WNDRP",
    "Westerbeek": "WRBEEK",
    "Westerbork": "WRBORK",
    "Westerbroek": "WRBROE",
    "Westeremden": "WREMDN",
    "Westergeest": "WRGEES",
    "Westerhaar-Vriezenv wijk": "WRHAAR",
    "Westerhoven": "WESTHV",
    "Westerland": "WRLAND",
    "Westerlee": "WRLEE",
    "Westernieland": "WRNIEL",
    "Westervelde": "WRVELD",
    "Westervoort": "WRVOOR",
    "Westerwijtwerd": "WRWIJT",
    "Westhem": "WESTHM",
    "Westhoek": "WHOEK",
    "Westkapelle": "WKAPLL",
    "Westknollendam": "WKNOLD",
    "Westmaas": "WMAAS",
    "Westwoud": "WWOUD",
    "Westzaan": "WZAAN",
    "Wetering": "WETERG",
    "Weteringbrug": "WETEBG",
    "Wetsens": "WETSNS",
    "Wetsinge": "WETSNG",
    "Weurt": "WEURT",
    "Wezep": "WEZEP",
    "Wezup": "WEZUP",
    "Wezuperbrug": "WEZUPB",
    "Wichmond": "WICHMD",
    "Wier": "WIER",
    "Wierden": "WIERDN",
    "Wieringerwaard": "WIERWD",
    "Wieringerwerf": "WIERWF",
    "Wierum": "WIERUM",
    "Wijchen": "WIJCHN",
    "Wijckel": "WIJCKL",
    "Wijdenes": "WIJDNS",
    "Wijdewormer": "WIJDWR",
    "Wijhe": "WIJHE",
    "Wijk aan Zee": "WIJKAZ",
    "Wijk bij Duurstede": "WIJKDS",
    "Wijk en Aalburg": "WIJKAB",
    "Wijlre": "WIJLRE",
    "Wijnaldum": "WIJNAL",
    "Wijnandsrade": "WIJNRD",
    "Wijnbergen": "WIJNBG",
    "Wijngaarden": "WIJNGD",
    "Wijnjewoude": "WIJNWD",
    "Wijster": "WIJSTR",
    "Wilbertoord": "WILBRT",
    "Wildervank": "WILDVK",
    "Wilhelminadorp": "WILHDP",
    "Wilhelminaoord": "WILHOO",
    "Willemsoord": "WILLOO",
    "Willemstad": "WILLST",
    "Wilnis": "WILNIS",
    "Wilp": "WILP",
    "Wilsum": "WILSUM",
    "Winde": "WINDE",
    "Windraak": "WINDRK",
    "Winkel": "WINKEL",
    "Winneweer": "WINNWR",
    "Winschoten": "WINSCH",
    "Winssen": "WINSSN",
    "Winsum Fr": "WINSFR",
    "Winsum GR": "WINSGR",
    "Wintelre": "WINTLR",
    "Winterswijk": "WINTWK",
    "Winterswijk Brinkheurne": "WINTBR",
    "Winterswijk Corle": "WINTCO",
    "Winterswijk Henxel": "WINTHX",
    "Winterswijk Huppel": "WINTHU",
    "Winterswijk Kotten": "WINTKO",
    "Winterswijk Meddo": "WINTME",
    "Winterswijk Miste": "WINTMI",
    "Winterswijk Ratum": "WINTRA",
    "Winterswijk Woold": "WINTWO",
    "Wirdum Fr": "WIRDFR",
    "Wirdum Gn": "WIRDGR",
    "Wissenkerke": "WISSKK",
    "Witharen": "WITHRN",
    "Witmarsum": "WITMSM",
    "Witte Paarden": "WITTEP",
    "Wittelte": "WITTLT",
    "Wittem": "WITTEM",
    "Witteveen": "WITTVN",
    "Wiuwert": "WIUWRT",
    "Wjelsryp": "WJELSP",
    "Woerden": "WOERDN",
    "Woerdense Verlaat": "WOEVRL",
    "Wognum": "WOGNUM",
    "Woldendorp": "WOLDDP",
    "Wolfheze": "WOLFHZ",
    "Wolphaartsdijk": "WOLPHD",
    "Wolsum": "WOLSUM",
    "Woltersum": "WOLTSM",
    "Wolvega": "WOLVGA",
    "Wommels": "WOMMLS",
    "Wons": "WONS",
    "Workum": "WORKUM",
    "Wormer": "WORMER",
    "Wormerveer": "WORMVR",
    "Woubrugge": "WOUBRG",
    "Woudbloem": "WOUDBL",
    "Woudenberg": "WOUDBG",
    "Woudrichem": "WOUDRM",
    "Woudsend": "WOUDSD",
    "Wouw": "WOUW",
    "Wouwse Plantage": "WOUWPL",
    "Wyns": "WYNS",
    "Wytgaard": "WYTGRD",
    "Yde": "YDE",
    "Yerseke": "YERSKE",
    "Ypecolsga": "YPECLS",
    "Ysbrechtum": "YSBRCH",
    "Ysselsteyn LI": "YSSELS",
    "Zaamslag": "ZAAMSL",
    "Zaandam": "ZAANDM",
    "Zaandijk": "ZAANDK",
    "Zalk": "ZALK",
    "Zaltbommel": "ZALTBM",
    "Zandberg": "ZANDBG",
    "Zandeweer": "ZANDWR",
    "Zandhuizen": "ZANDHZ",
    "Zandpol": "ZANDPL",
    "Zandvoort": "ZANDVT",
    "Zeddam": "ZEDDAM",
    "Zeegse": "ZEEGSE",
    "Zeeland": "ZEELND",
    "Zeerijp": "ZEERP",
    "Zeewolde": "ZEEWLD",
    "Zegge": "ZEGGE",
    "Zegveld": "ZEGVLD",
    "Zeijen": "ZEIJEN",
    "Zeijerveen": "ZEIJRV",
    "Zeijerveld": "ZEIJRD",
    "Zeist": "ZEIST",
    "Zelhem": "ZELHEM",
    "Zenderen": "ZENDRN",
    "Zennewijnen": "ZENWTL",
    "Zennewijnen Neerijnen": "ZENWNR",
    "Zetten": "ZETTEN",
    "Zevenaar": "ZEVENR",
    "Zevenbergen": "ZEVENB",
    "Zevenbergschen Hoek": "ZEVBHM",
    "Zevenbergschen Hoek Dri": "ZEVBHD",
    "Zevenhoven": "ZEVNHV",
    "Zevenhuizen GR": "ZEVHGR",
    "Zevenhuizen ZH": "ZEVHZH",
    "Zierikzee": "ZIERKZ",
    "Zieuwent": "ZIEUWT",
    "Zijderveld": "ZIJDVD",
    "Zijdewind": "ZIJDWD",
    "Zijldijk": "ZIJLDK",
    "Zoelen": "ZOELEN",
    "Zoelmond": "ZOELMD",
    "Zoetermeer": "ZOETMR",
    "Zoeterwoude": "ZOETWD",
    "Zonnemaire": "ZONNEM",
    "Zorgvlied": "ZORGVL",
    "Zoutelande": "ZOUTLD",
    "Zoutkamp": "ZOUTKP",
    "Zuid-Beijerland": "ZBEIJL",
    "Zuid-Scharwoude": "ZSCHAR",
    "Zuidbroek": "ZBROEK",
    "Zuiddorpe": "ZDORPP",
    "Zuidermeer": "ZRMEER",
    "Zuiderwoude": "ZRWOUD",
    "Zuidhorn": "ZHORN",
    "Zuidlaarderveen": "ZLAARV",
    "Zuidland": "ZLAND",
    "Zuidlaren": "ZLAREN",
    "Zuidoostbeemster": "ZOBEEM",
    "Zuidschermer": "ZSCHER",
    "Zuidveen": "ZVEEN",
    "Zuidveld": "ZVELD",
    "Zuidvelde Noordenveld": "ZVELDE",
    "Zuidwolde DR": "ZWLDDR",
    "Zuidwolde GR": "ZWLDGR",
    "Zuidzande": "ZZANDE",
    "Zuilichem": "ZUILCH",
    "Zuna": "ZUNA",
    "Zundert": "ZUNDRT",
    "Zurich": "ZURICH",
    "Zutphen": "ZUTPHN",
    "Zuurdijk": "ZUURDK",
    "Zwaag": "ZWAAG",
    "Zwaagdijk-Oost": "ZWAAGO",
    "Zwaagdijk-West": "ZWAAGW",
    "Zwaanshoek": "ZWAANH",
    "Zwagerbosch": "ZWAGRB",
    "Zwammerdam": "ZWAMMD",
    "Zwanenburg": "ZWANBG",
    "Zwartebroek": "ZWARTB",
    "Zwartemeer": "ZWARTM",
    "Zwartewaal": "ZWARTW",
    "Zwartsluis": "ZWARTS",
    "Zweeloo": "ZWEELO",
    "Zweins": "ZWEINS",
    "Zwiggelte": "ZWIGGT",
    "Zwijndrecht": "ZWIJND",
    "Zwinderen": "ZWINDR",
    "Zwolle": "ZWOLLE",
    "de Hoef": "DEHOEF",
    "de Lutte": "DELUTT",
    "de Wijk": "DEWIJK",
    "de Woude": "DEWOUD",
}

# Create reverse lookup: abbreviation -> city name
ABBREVIATION_TO_CITY = {abbrev: city for city, abbrev in CITY_ABBREVIATIONS.items()}


def get_abbreviation(city: str) -> str:
    """Get abbreviation for a city name, or empty string if not found."""
    return CITY_ABBREVIATIONS.get(city, "")


def get_city_from_abbreviation(abbrev: str) -> str:
    """Get full city name from abbreviation, or empty string if not found."""
    return ABBREVIATION_TO_CITY.get(abbrev.upper(), "")
